'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {ReactFlow,Background,Controls,MiniMap,addEdge,useNodesState,useEdgesState,Handle,Position,MarkerType,NodeProps} from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import {Activity,ArrowLeft,CheckCircle2,Clock3,Database,GitBranch,Globe2,Mail,Plus,Save,Search,Settings2,ShieldCheck,Sparkles,Terminal,Users,Webhook,Zap,Play,Power,Network,PenTool} from 'lucide-react';
import {sb} from '../lib/switchboard';

type RunState='idle'|'running'|'done'|'failed';
type NodeData={label:string;kind:string;subtitle?:string;status?:RunState;config?:Record<string,any>;retry?:number};
const nodeLibrary=[['trigger','Trigger','Input',Zap],['http','HTTP Request','Integration',Globe2],['postgres','PostgreSQL','Data',Database],['webhook','Webhook','Input',Webhook],['ssh','SSH Action','Systems',Terminal],['powershell','PowerShell','Systems',Terminal],['email','Send Email','Messaging',Mail],['approval','Approval','Control',Clock3],['condition','Condition','Logic',GitBranch],['delay','Delay','Control',Clock3],['createUser','Create User','Directory',Users],['disableUser','Disable User','Directory',Users],['addGroup','Add Group','Access',ShieldCheck],['assignLicense','Assign License','Access',Sparkles],['health','Health Check','Monitoring',Activity]] as const;
const icons:any={trigger:Zap,http:Globe2,postgres:Database,webhook:Webhook,ssh:Terminal,powershell:Terminal,email:Mail,approval:Clock3,condition:GitBranch,delay:Clock3,createUser:Users,disableUser:Users,addGroup:ShieldCheck,assignLicense:Sparkles,health:Activity};
const slots=[{x:13,y:39},{x:23,y:67},{x:76,y:31},{x:81,y:52},{x:73,y:72},{x:54,y:82},{x:88,y:77},{x:15,y:79}];
function FlowNode({data,selected}:NodeProps){const d=data as NodeData;const Icon=icons[d.kind]||Zap;return <div className={`builder-node ${selected?'selected':''} ${d.status||''}`}><Handle type="target" position={Position.Top}/><div className="builder-node-head"><span><Icon size={15}/></span><small>{d.kind}</small>{d.status==='done'&&<CheckCircle2 size={14}/>}</div><b>{d.label}</b><p>{d.subtitle||'Ready to configure'}</p><Handle type="source" position={Position.Bottom}/></div>}
function VisualNode({node,index}:{node:any;index:number}){const d=node.data as NodeData;const Icon=icons[d.kind]||Zap;const p=slots[index%slots.length];return <div className={`viz-node ${d.status||'idle'}`} style={{left:`${p.x}%`,top:`${p.y}%`}}><div className="viz-bracket"/><span className="viz-icon"><Icon size={17}/></span><div><b>{d.label}</b><small>{String(d.kind).toUpperCase()}</small></div>{d.status==='running'&&<i className="viz-live-dot"/>}</div>}

export function BuilderClient({workflowId}:{workflowId:string}){
 const [nodes,setNodes,onNodesChange]=useNodesState<any>([]),[edges,setEdges,onEdgesChange]=useEdgesState<any>([]);const [workflow,setWorkflow]=useState<any>(null),[selected,setSelected]=useState<any>(null),[query,setQuery]=useState(''),[logs,setLogs]=useState<string[]>([]),[running,setRunning]=useState(false),[notice,setNotice]=useState('Loading…'),[runMeta,setRunMeta]=useState<any>(null),[view,setView]=useState<'visual'|'edit'>('visual'),[elapsed,setElapsed]=useState(0),[startedAt,setStartedAt]=useState<number|null>(null);
 const nodeTypes=useMemo(()=>({custom:FlowNode}),[]);
 useEffect(()=>{sb<any>(`/workflows/${workflowId}`).then(w=>{setWorkflow(w);const def=w.definition||{};setNodes((def.nodes||[]).map((n:any)=>({...n,type:'custom',data:{...n.data,status:'idle'}})));setEdges((def.edges||[]).map((e:any)=>({...e,animated:false,markerEnd:{type:MarkerType.ArrowClosed}})));setNotice('READY')}).catch(e=>setNotice(e.message))},[workflowId,setNodes,setEdges]);
 useEffect(()=>{if(!running||!startedAt)return;const t=setInterval(()=>setElapsed(Date.now()-startedAt),250);return()=>clearInterval(t)},[running,startedAt]);
 const onConnect=useCallback((p:any)=>setEdges(es=>addEdge({...p,markerEnd:{type:MarkerType.ArrowClosed}},es)),[setEdges]);
 const definition=()=>({nodes:nodes.map(n=>({...n,type:undefined,data:{...n.data,status:undefined}})),edges:edges.map(e=>({...e,animated:undefined,markerEnd:undefined,className:undefined}))});
 const save=async()=>{setNotice('SAVING');const w=await sb<any>(`/workflows/${workflowId}`,{method:'PUT',body:JSON.stringify({definition:definition()})});setWorkflow(w);setNotice(`SAVED · V${w.version}`);return w};
 const toggleActive=async()=>{if(!workflow)return;const status=workflow.status==='ACTIVE'?'DRAFT':'ACTIVE';const w=await sb<any>(`/workflows/${workflowId}`,{method:'PUT',body:JSON.stringify({status})});setWorkflow(w);setNotice(status)};
 const run=async()=>{if(running)return;setView('visual');setRunning(true);setElapsed(0);setStartedAt(Date.now());setRunMeta(null);setLogs([]);setNodes(ns=>ns.map(n=>({...n,data:{...n.data,status:'idle'}})));try{await save();const r=await sb<any>(`/workflows/${workflowId}/run`,{method:'POST',body:JSON.stringify({triggerType:'manual',payload:{source:'visual-map',initiatedAt:new Date().toISOString()}})});let terminal=false;while(!terminal){await new Promise(x=>setTimeout(x,650));const current=await sb<any>(`/runs/${r.id}`);setRunMeta(current);setLogs((current.logs||[]).map((x:any)=>x.message));const states=new Map<string,string>((current.steps||[]).map((s:any)=>[String(s.nodeId),String(s.status)] as [string,string]));setNodes(ns=>ns.map(n=>{const s=states.get(n.id);return {...n,data:{...n.data,status:s==='RUNNING'?'running':s==='SUCCEEDED'?'done':s==='FAILED'?'failed':'idle'}}}));terminal=['SUCCEEDED','FAILED','WAITING','CANCELLED'].includes(current.status);setNotice(current.status)}}catch(e:any){setNotice('FAILED');setLogs(l=>[...l,e.message])}finally{setRunning(false)}};
 const addNode=(kind:string,label:string)=>setNodes(ns=>[...ns,{id:crypto.randomUUID(),type:'custom',position:{x:300+Math.random()*260,y:120+Math.random()*360},data:{label,kind,status:'idle',config:{}}}]);
 const total=Math.max(nodes.length,1),done=(runMeta?.steps||[]).filter((s:any)=>s.status==='SUCCEEDED').length,failed=(runMeta?.steps||[]).filter((s:any)=>s.status==='FAILED').length,delivered=done,missed=failed,progress=Math.round(((done+failed)/total)*100);
 const source=nodes[0],subs=nodes.slice(1,9),sourceSlot={x:31,y:50},hub={x:50,y:58};
 const filtered=nodeLibrary.filter(n=>`${n[1]} ${n[2]}`.toLowerCase().includes(query.toLowerCase()));
 return <div className={`switchboard-experience ${view}`}>
  <div className="experience-topbar"><button onClick={()=>history.back()} className="ghost-icon"><ArrowLeft size={16}/></button><div className="experience-brand"><Network size={15}/><span>SWITCHBOARD</span><em>{workflow?.name||'WORKFLOW'}</em></div><div className="experience-actions"><span className={`run-state ${running?'live':''}`}>{running?'LIVE':notice}</span><button onClick={()=>setView(view==='visual'?'edit':'visual')} className="ghost-btn">{view==='visual'?<><PenTool size={14}/> EDIT</>:<><Network size={14}/> VISUALIZE</>}</button><button onClick={toggleActive} className="ghost-btn"><Power size={14}/>{workflow?.status||'DRAFT'}</button><button onClick={run} disabled={running} className="run-btn"><Play size={14}/>{running?'RUNNING':'RUN'}</button></div></div>
  {view==='visual'?<section className="event-map">
    <div className="event-map-title"><small>3 SENDS&nbsp;&nbsp;VS&nbsp;&nbsp;1 PUBLISH</small><h1>Pub/Sub</h1><p>publish once, every subscriber gets a copy.</p><span>how do services hear about ONE order?</span></div>
    <div className="score score-left"><b>{missed}</b><small>MISSED</small></div><div className="score score-right"><b>{delivered}</b><small>DELIVERED</small></div>
    {source&&<div className={`publisher-card ${source.data.status||''}`} style={{left:`${sourceSlot.x}%`,top:`${sourceSlot.y}%`}}><span className="publisher-grid">•••<br/>•••<br/>•••</span><b>{source.data.label}</b><small>the publisher</small></div>}
    <div className={`topic-hub ${running?'active':''}`} style={{left:`${hub.x}%`,top:`${hub.y}%`}}><div className="hub-ring r1"/><div className="hub-ring r2"/><div className="hub-core"><Network size={18}/><small>TOPIC</small><b>{workflow?.slug||'event-stream'}</b></div></div>
    <svg className="route-layer" viewBox="0 0 1000 700" preserveAspectRatio="none">
      <path id="p0" d="M310 350 C390 360 430 390 500 405" className="route"/>
      {subs.map((n:any,i:number)=>{const p=slots[i%slots.length];const x=p.x*10,y=p.y*7;const d=`M500 405 C${560+i*15} ${385+i*8} ${x-40} ${y} ${x} ${y}`;return <g key={n.id}><path id={`p${i+1}`} d={d} className={`route ${n.data.status==='done'?'done':''} ${n.data.status==='failed'?'failed':''}`}/>{(running||n.data.status==='done')&&<circle r="4" className="packet"><animateMotion dur={`${1.5+i*.12}s`} repeatCount="indefinite" path={d}/></circle>}</g>})}
      {running&&<circle r="4" className="packet source-packet"><animateMotion dur="1.2s" repeatCount="indefinite" path="M310 350 C390 360 430 390 500 405"/></circle>}
    </svg>
    {subs.map((n:any,i:number)=><VisualNode key={n.id} node={n} index={i}/>) }
    <div className="map-caption">{logs.at(-1)|| (running?'publishing event…':'one event, many independent subscribers')}</div>
    <div className="map-footer"><span>PUB/SUB · PUBLISH ONCE · A COPY PER SUBSCRIBER</span><span>{progress}% COMPLETE · {(elapsed/1000).toFixed(1)}s</span></div>
  </section>:
  <section className="editor-layout"><aside className="editor-library"><div className="editor-heading">NODE LIBRARY <span>{nodeLibrary.length}</span></div><div className="builder-search"><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search nodes"/></div>{filtered.map(([kind,label,cat,Icon])=><button key={kind} onClick={()=>addNode(kind,label)}><Icon size={15}/><span><b>{label}</b><small>{cat}</small></span><Plus size={13}/></button>)}</aside><div className="editor-canvas"><ReactFlow nodes={nodes} edges={edges} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} onConnect={onConnect} onNodeClick={(_,n)=>setSelected(n)} nodeTypes={nodeTypes} fitView><Background gap={28}/><MiniMap/><Controls/></ReactFlow><div className="editor-save"><button onClick={save}><Save size={14}/> SAVE</button></div></div><aside className="editor-inspector"><div className="editor-heading">INSPECTOR</div>{selected?<><Settings2 size={18}/><h3>{selected.data.label}</h3><label>Display name<input value={selected.data.label} onChange={e=>{const label=e.target.value;setSelected({...selected,data:{...selected.data,label}});setNodes(ns=>ns.map(n=>n.id===selected.id?{...n,data:{...n.data,label}}:n))}}/></label><label>Config JSON<textarea value={JSON.stringify(selected.data.config||{},null,2)} onChange={e=>{try{const config=JSON.parse(e.target.value);setSelected({...selected,data:{...selected.data,config}});setNodes(ns=>ns.map(n=>n.id===selected.id?{...n,data:{...n.data,config}}:n))}catch{}}}/></label></>:<p>Select a node to configure it.</p>}</aside></section>}
 </div>
}
