'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {ReactFlow,Background,Controls,MiniMap,addEdge,useNodesState,useEdgesState,Handle,Position,MarkerType,NodeProps} from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import './n8n-builder.css';
import {Activity,ArrowLeft,CheckCircle2,Clock3,Database,GitBranch,Globe2,Mail,Plus,Save,Search,ShieldCheck,Sparkles,Terminal,Users,Webhook,Zap,Play,Power,X,Workflow,History,Trash2,Undo2,Redo2,CopyPlus} from 'lucide-react';
import {PayloadEditor} from './PayloadEditor';
import {RequestFields} from './RequestFields';
import {TriggerConfig} from './TriggerConfig';
import {getSession,sb} from '../lib/switchboard';

type RunState='idle'|'running'|'done'|'failed'|'waiting'|'skipped';
type NodeData={label:string;kind:string;subtitle?:string;status?:RunState;config?:Record<string,any>;retry?:number;continueOnFailure?:boolean;warnings?:string[]};
type Snapshot={nodes:any[];edges:any[]};
const nodeLibrary=[['trigger','Manual Trigger','Input',Zap],['http','HTTP Request','Integration',Globe2],['postgres','PostgreSQL','Data',Database],['webhook','Webhook','Input',Webhook],['schedule','Schedule Trigger','Input',Clock3],['ssh','SSH Action','Systems',Terminal],['powershell','PowerShell','Systems',Terminal],['email','Send Email','Messaging',Mail],['approval','Approval','Control',Clock3],['condition','Condition','Logic',GitBranch],['delay','Delay','Control',Clock3],['createUser','Create User','Directory',Users],['disableUser','Disable User','Directory',Users],['addGroup','Add Group','Access',ShieldCheck],['assignLicense','Assign License','Access',Sparkles],['removeGroup','Remove Group','Access',ShieldCheck],['revokeLicense','Revoke License','Access',Sparkles],['health','Health Check','Monitoring',Activity]] as const;
const icons:any={schedule:Clock3,removeGroup:ShieldCheck,revokeLicense:Sparkles,trigger:Zap,http:Globe2,postgres:Database,webhook:Webhook,ssh:Terminal,powershell:Terminal,email:Mail,approval:Clock3,condition:GitBranch,delay:Clock3,createUser:Users,disableUser:Users,addGroup:ShieldCheck,assignLicense:Sparkles,health:Activity};
const defaults=(kind:string)=>kind==='schedule'?{every:5,unit:'minutes'}:kind==='removeGroup'?{email:'{{trigger.email}}',group:'Employees'}:kind==='revokeLicense'?{email:'{{trigger.email}}',license:'Standard'}:kind==='delay'?{ms:1000}:kind==='health'?{url:'https://switchboard-api-tqc3.onrender.com/health',timeoutMs:8000}:kind==='http'?{method:'GET',url:'https://switchboard-api-tqc3.onrender.com/health',timeoutMs:15000}:kind==='condition'?{field:'trigger.department',operator:'equals',value:'IT'}:kind==='createUser'?{email:'{{trigger.email}}',fullName:'{{trigger.fullName}}',department:'{{trigger.department}}'}:kind==='disableUser'?{email:'{{trigger.email}}'}:kind==='addGroup'?{email:'{{trigger.email}}',group:'Employees'}:kind==='assignLicense'?{email:'{{trigger.email}}',license:'Standard'}:kind==='email'?{to:'{{trigger.email}}',subject:'Welcome',text:'Welcome to the team'}:{};

function FlowNode({data,selected,id}:NodeProps){const d=data as NodeData;const Icon=icons[d.kind]||Zap;const condition=d.kind==='condition';return <div className={`n8n-node ${selected?'selected':''} ${d.status||''} ${d.warnings?.length?'invalid':''}`}><Handle type="target" position={Position.Left}/><div className="n8n-node-top"><span className="n8n-node-icon"><Icon size={16}/></span><span><b>{d.label}</b><small>{d.kind}</small></span>{d.status==='running'?<Activity size={14} className="spin"/>:d.status==='done'?<CheckCircle2 size={14}/>:null}</div><div className="n8n-node-body">{d.warnings?.length?<span role="status">{d.warnings[0]}</span>:null}{d.status==='running'?'Executing…':d.status==='done'?'Execution complete':d.status==='failed'?'Execution failed':d.status==='waiting'?'Waiting for approval':d.status==='skipped'?'Path skipped':d.subtitle||'Click to configure'}</div>{condition?<><Handle id="true" className="condition-handle true" type="source" position={Position.Right} style={{top:'38%'}}/><Handle id="false" className="condition-handle false" type="source" position={Position.Right} style={{top:'72%'}}/><span className="branch-label true">TRUE</span><span className="branch-label false">FALSE</span>{['true','false'].map(handle=><button key={handle} className="node-add-next" style={{top:handle==='true'?'38%':'72%'}} title={`Add ${handle.toUpperCase()} branch`} onClick={e=>{e.stopPropagation();window.dispatchEvent(new CustomEvent('switchboard:add-after',{detail:{nodeId:id,handle}}))}}><Plus size={11}/></button>)}</>:<><Handle type="source" position={Position.Right}/><button className="node-add-next" title="Add next node" onClick={e=>{e.stopPropagation();window.dispatchEvent(new CustomEvent('switchboard:add-after',{detail:{nodeId:id}}))}}><Plus size={11}/></button></>}</div>}

function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="n8n-field"><span>{label}</span>{children}</label>}
function ConfigFields({node,credentials,update}:{node:any;credentials:any[];update:(config:any)=>void}){const kind=String(node.data.kind),c=node.data.config||{};const set=(key:string,value:any)=>update({...c,[key]:value});const cred=<Field label="Credential"><select value={c.credentialRef||''} onChange={e=>set('credentialRef',e.target.value||undefined)}><option value="">No saved credential</option>{credentials.filter(x=>({http:['API_KEY','BASIC_AUTH'],postgres:['POSTGRES'],ssh:['SSH'],powershell:['SSH'],email:['SMTP']} as Record<string,string[]>)[kind]?.includes(x.type)).map(x=><option key={x.id} value={x.id}>{x.name} · {x.type}</option>)}</select></Field>;
 if(kind==='trigger'||kind==='webhook'||kind==='approval')return <p className="node-help">{kind==='trigger'?'Input is provided when you execute the workflow.':kind==='webhook'?'Webhook payload becomes the trigger input.':'Execution pauses here until an operator approves or rejects the run.'}</p>;
 if(kind==='schedule')return <><Field label="Interval"><input type="number" min="1" value={c.every||5} onChange={e=>set('every',Number(e.target.value))}/></Field><Field label="Unit"><select value={c.unit||'minutes'} onChange={e=>set('unit',e.target.value)}><option>minutes</option><option>hours</option><option>days</option></select></Field></>;
 if(kind==='delay'){const unit=c.unit||'seconds',factor=unit==='milliseconds'?1:unit==='minutes'?60000:1000;return <><Field label="Duration"><input type="number" min="0" step="any" max={30000/factor} value={(c.ms??1000)/factor} onChange={e=>update({...c,ms:Number(e.target.value)*factor})}/></Field><Field label="Unit"><select value={unit} onChange={e=>set('unit',e.target.value)}><option>milliseconds</option><option>seconds</option><option>minutes</option></select></Field><p className="node-help">Maximum delay: 30 seconds per node.</p></>};
 if(kind==='health')return <><Field label="Health URL"><input value={c.url||''} onChange={e=>set('url',e.target.value)} placeholder="https://service/health"/></Field><Field label="Timeout (ms)"><input type="number" value={c.timeoutMs??8000} onChange={e=>set('timeoutMs',Number(e.target.value))}/></Field></>;
 if(kind==='http')return <>{cred}<Field label="Method"><select value={c.method||'GET'} onChange={e=>set('method',e.target.value)}><option>GET</option><option>POST</option><option>PUT</option><option>PATCH</option><option>DELETE</option></select></Field><Field label="URL"><input value={c.url||''} onChange={e=>set('url',e.target.value)} placeholder="https://api.example.com"/></Field><Field label="Timeout (ms)"><input type="number" value={c.timeoutMs??15000} onChange={e=>set('timeoutMs',Number(e.target.value))}/></Field></>;
 if(kind==='condition')return <><Field label="Field"><input value={c.field||''} onChange={e=>set('field',e.target.value)} placeholder="trigger.department"/></Field><Field label="Operator"><select value={c.operator||'equals'} onChange={e=>set('operator',e.target.value)}><option value="equals">Equals</option><option value="notEquals">Does not equal</option><option value="gt">Greater than</option><option value="lt">Less than</option><option value="contains">Contains</option><option value="exists">Exists</option><option value="truthy">Truthy</option></select></Field><Field label="Expected value"><input value={c.value??''} onChange={e=>set('value',e.target.value)}/></Field><div className="branch-help"><span><i className="branch-dot true"/>TRUE output</span><span><i className="branch-dot false"/>FALSE output</span></div></>;
 if(kind==='postgres')return <>{cred}<Field label="Host override (optional)"><input value={c.host||''} onChange={e=>set('host',e.target.value)} placeholder="Use the credential host"/></Field><Field label="Database override (optional)"><input value={c.database||''} onChange={e=>set('database',e.target.value)}/></Field><Field label="SQL query"><textarea value={c.query||''} onChange={e=>set('query',e.target.value)} placeholder="select now();"/></Field></>;
 if(kind==='ssh'||kind==='powershell')return <>{cred}<Field label="Host"><input value={c.host||''} onChange={e=>set('host',e.target.value)}/></Field><Field label="Username"><input value={c.username||''} onChange={e=>set('username',e.target.value)}/></Field><Field label="Command"><textarea value={c.command||''} onChange={e=>set('command',e.target.value)} placeholder={kind==='powershell'?'Get-Service':'uname -a'}/></Field></>;
 if(kind==='email')return <>{cred}<Field label="To"><input value={c.to||''} onChange={e=>set('to',e.target.value)} placeholder="{{trigger.email}}"/></Field><Field label="Subject"><input value={c.subject||''} onChange={e=>set('subject',e.target.value)}/></Field><Field label="Message"><textarea value={c.text||''} onChange={e=>set('text',e.target.value)}/></Field></>;
 if(kind==='createUser')return <><Field label="Email"><input value={c.email||''} onChange={e=>set('email',e.target.value)} placeholder="{{trigger.email}}"/></Field><Field label="Full name"><input value={c.fullName||''} onChange={e=>set('fullName',e.target.value)} placeholder="{{trigger.fullName}}"/></Field><Field label="Department"><input value={c.department||''} onChange={e=>set('department',e.target.value)}/></Field><Field label="Title"><input value={c.title||''} onChange={e=>set('title',e.target.value)}/></Field></>;
 if(['disableUser','addGroup','removeGroup','assignLicense','revokeLicense'].includes(kind))return <><Field label="User email"><input value={c.email||''} onChange={e=>set('email',e.target.value)} placeholder="{{trigger.email}}"/></Field>{['addGroup','removeGroup'].includes(kind)&&<Field label="Group"><input value={c.group||''} onChange={e=>set('group',e.target.value)}/></Field>}{['assignLicense','revokeLicense'].includes(kind)&&<Field label="License"><input value={c.license||''} onChange={e=>set('license',e.target.value)}/></Field>}</>;
 return <Field label="Configuration JSON"><textarea value={JSON.stringify(c,null,2)} readOnly/></Field>;
}

export function BuilderClient({workflowId}:{workflowId:string}){
 const[nodes,setNodes,onNodesChange]=useNodesState<any>([]),[edges,setEdges,onEdgesChange]=useEdgesState<any>([]);
 const[workflow,setWorkflow]=useState<any>(null),[selected,setSelected]=useState<any>(null),[query,setQuery]=useState(''),[showAdd,setShowAdd]=useState(false),[logs,setLogs]=useState<string[]>([]),[running,setRunning]=useState(false),[notice,setNotice]=useState('Loading…'),[runMeta,setRunMeta]=useState<any>(null),[credentials,setCredentials]=useState<any[]>([]),[showTest,setShowTest]=useState(false),[testPayload,setTestPayload]=useState('{\n  "email": "test@example.com",\n  "fullName": "Test User",\n  "department": "IT"\n}'),[payloadError,setPayloadError]=useState(''),[showHistory,setShowHistory]=useState(false),[historyRuns,setHistoryRuns]=useState<any[]>([]),[dirty,setDirty]=useState(false),[pendingSource,setPendingSource]=useState<string>(''),[validationError,setValidationError]=useState('');
 const [,refreshHistory]=useState(0);
 const [fieldErrors,setFieldErrors]=useState<Record<string,Record<string,string>>>({});
 const [showSnapshot,setShowSnapshot]=useState(false);
 const session=getSession();const canEdit=session?.user?.role==='ADMIN'||(session?.user?.role==='OPERATOR'&&workflow?.ownerId===session?.user?.id);const canRun=session?.user?.role!=='VIEWER';
 const [flow,setFlow]=useState<any>(null);
 const canvasRef=useRef<HTMLDivElement>(null);
 const [pendingHandle,setPendingHandle]=useState<string|undefined>();
 useEffect(()=>{if(!flow||!canvasRef.current)return;let timer:ReturnType<typeof setTimeout>;const fit=()=>{clearTimeout(timer);timer=setTimeout(()=>void flow.fitView({padding:.25,maxZoom:1,duration:180}),120)};const observer=new ResizeObserver(fit);observer.observe(canvasRef.current);return()=>{clearTimeout(timer);observer.disconnect()}},[flow]);
 useEffect(()=>{if(!flow)return;const timer=setTimeout(()=>void flow.fitView({padding:.25,maxZoom:1,duration:180}),120);return()=>clearTimeout(timer)},[flow,nodes.length,showSnapshot]);
 const saveChain=useRef<Promise<unknown>>(Promise.resolve()),currentDefinition=useRef('');
 const nodeTypes=useMemo(()=>({custom:FlowNode}),[]);const loaded=useRef(false),suppressHistory=useRef(false),history=useRef<Snapshot[]>([]),historyIndex=useRef(-1),clipboard=useRef<any>(null),autosaveTimer=useRef<any>(null),historyTimer=useRef<any>(null);
 const snapshot=()=>({nodes:nodes.map(n=>({...n,data:{...n.data}})),edges:edges.map(e=>({...e,data:e.data?{...e.data}:e.data}))});
 const seedHistory=(s:Snapshot)=>{history.current=[s];historyIndex.current=0};
 const restore=(s:Snapshot)=>{suppressHistory.current=true;setNodes(s.nodes.map(n=>({...n,data:{...n.data}})));setEdges(s.edges.map(e=>({...e,data:e.data?{...e.data}:e.data})));setSelected(null);setDirty(true);setTimeout(()=>{suppressHistory.current=false},0)};
 const undo=()=>{if(historyIndex.current<=0)return;historyIndex.current--;restore(history.current[historyIndex.current])};
 const redo=()=>{if(historyIndex.current>=history.current.length-1)return;historyIndex.current++;restore(history.current[historyIndex.current])};
 useEffect(()=>{sb<any>(`/workflows/${workflowId}`).then(w=>{setWorkflow(w);const def=w.definition||{};const ns=(def.nodes||[]).map((n:any)=>({...n,type:'custom',data:{...n.data,status:'idle',config:{...defaults(n.data?.kind),...(n.data?.config||{})}}}));const es=(def.edges||[]).map((e:any,i:number)=>({...e,id:e.id||`edge-${e.source}-${e.target}-${i}`,animated:false,markerEnd:{type:MarkerType.ArrowClosed},label:e.data?.when===undefined?undefined:String(e.data.when).toUpperCase()}));setNodes(ns);setEdges(es);seedHistory({nodes:ns,edges:es});loaded.current=true;setDirty(false);setNotice('Saved')}).catch(e=>setNotice(e.message));sb<any[]>('/credentials').then(setCredentials).catch(()=>{})},[workflowId,setNodes,setEdges]);
 useEffect(()=>{const h=(e:any)=>{setPendingSource(String(e.detail?.nodeId||''));setPendingHandle(e.detail?.handle);setSelected(null);setShowTest(false);setShowHistory(false);setShowAdd(true)};window.addEventListener('switchboard:add-after',h);return()=>window.removeEventListener('switchboard:add-after',h)},[]);
 const loadHistory=async()=>{try{setHistoryRuns(await sb<any[]>(`/runs?workflowId=${workflowId}`))}catch{}};
 const onConnect=useCallback((p:any)=>setEdges(es=>{const source=nodes.find(n=>n.id===p.source);const when=source?.data?.kind==='condition'&&p.sourceHandle?String(p.sourceHandle):undefined;return addEdge({...p,id:`edge-${crypto.randomUUID()}`,data:when?{when}:undefined,label:when?.toUpperCase(),animated:false,markerEnd:{type:MarkerType.ArrowClosed}},es)}),[setEdges,nodes]);
 const definition=()=>({nodes:nodes.map(n=>({id:String(n.id),type:'custom',position:{x:Number(n.position?.x||0),y:Number(n.position?.y||0)},data:{...n.data,status:undefined,warnings:undefined,config:{...defaults(String(n.data?.kind||'')),...(n.data?.config||{})}}})),edges:edges.map((e:any,i:number)=>({id:String(e.id||`edge-${e.source}-${e.target}-${i}`),source:String(e.source),target:String(e.target),...(e.sourceHandle?{sourceHandle:String(e.sourceHandle)}:{}),...(e.data?{data:e.data}:{})}))});
 const validateLocal=()=>{if(!nodes.some(n=>['trigger','webhook','schedule'].includes(String(n.data?.kind))))return'Add a trigger node before running.';for(const n of nodes){const k=String(n.data?.kind),c=n.data?.config||{};if((k==='http'||k==='health')&&!c.url)return`${n.data.label} requires a URL.`;if(k==='postgres'&&((!c.credentialRef)||!c.query))return`${n.data.label} requires a database credential and query.`;if((k==='ssh'||k==='powershell')&&(((!c.host||!c.username)&&!c.credentialRef)||!c.command))return`${n.data.label} requires connection details and a command.`;if(k==='condition'){const routes=new Set(edges.filter(e=>e.source===n.id).map(e=>String(e.data?.when)));if(!routes.has('true')||!routes.has('false'))return`${n.data.label} needs TRUE and FALSE connections.`}}return''};
 currentDefinition.current=JSON.stringify(definition());
 const save=(silent=false):Promise<any>=>{
  const invalid=validateLocal();if(invalid){setValidationError(invalid);const affected=nodes.find(n=>invalid.startsWith(n.data.label));if(affected)setFieldErrors({[affected.id]:{configuration:invalid}});if(!silent)setNotice(`Fix: ${invalid}`);return Promise.reject(new Error(invalid))}
  const sent=definition(),serialized=JSON.stringify(sent);setValidationError('');setFieldErrors({});
  const operation=saveChain.current.catch(()=>{}).then(async()=>{
   if(!silent)setNotice('Saving…');
   try{const w=await sb<any>(`/workflows/${workflowId}`,{method:'PUT',body:JSON.stringify({definition:sent})});setWorkflow(w);setDirty(currentDefinition.current!==serialized);setNotice(`Saved · v${w.version}`);return w}catch(e:any){const errors:Record<string,Record<string,string>>={};for(const issue of e.issues||[]){const index=issue.path?.indexOf('nodes');const id=issue.nodeId||(index>=0?nodes[issue.path[index+1]]?.id:undefined);if(id)errors[id]={...errors[id],[issue.field||issue.path?.at(-1)||'configuration']:issue.message}}setFieldErrors(errors);setValidationError(e.message||'Save failed');setNotice(e.message||'Save failed');throw e}
  });saveChain.current=operation;return operation;
 };
 useEffect(()=>{if(!loaded.current||suppressHistory.current||!canEdit||showSnapshot)return;setDirty(true);clearTimeout(historyTimer.current);historyTimer.current=setTimeout(()=>{const s=snapshot();const serialized=JSON.stringify(s);const current=history.current[historyIndex.current];if(current&&JSON.stringify(current)===serialized)return;history.current=history.current.slice(0,historyIndex.current+1);history.current.push(s);if(history.current.length>50)history.current.shift();historyIndex.current=history.current.length-1;refreshHistory(v=>v+1)},250);clearTimeout(autosaveTimer.current);autosaveTimer.current=setTimeout(()=>{if(!validateLocal())void save(true).catch(()=>{})},1400);return()=>{clearTimeout(historyTimer.current);clearTimeout(autosaveTimer.current)}},[JSON.stringify(definition())]);
 const toggleActive=async()=>{if(!workflow)return;const status=workflow.status==='ACTIVE'?'DRAFT':'ACTIVE';setNotice('Updating…');try{await save();const w=await sb<any>(`/workflows/${workflowId}`,{method:'PUT',body:JSON.stringify({status})});setWorkflow(w);setNotice(status==='ACTIVE'?'Active':'Draft')}catch(e:any){setNotice(e.message||'Update failed')}};
 const addNode=(kind:string,label:string)=>{if(!canEdit||showSnapshot)return;const i=nodes.length;const source=nodes.find(n=>n.id===pendingSource);const id=crypto.randomUUID();const position=source?{x:(source.position?.x||0)+280,y:source.position?.y||140}:{x:250+(i%4)*250,y:140+Math.floor(i/4)*180};setNodes(ns=>[...ns,{id,type:'custom',position,data:{label,kind,subtitle:'Ready to configure',status:'idle',config:defaults(kind),retry:0}}]);if(source)setEdges(es=>addEdge({id:`edge-${crypto.randomUUID()}`,source:source.id,target:id,sourceHandle:pendingHandle,data:pendingHandle?{when:pendingHandle}:undefined,label:pendingHandle?.toUpperCase(),animated:false,markerEnd:{type:MarkerType.ArrowClosed}},es));setPendingSource('');setPendingHandle(undefined);setShowAdd(false)};
 const duplicateSelected=()=>{if(!selected||!canEdit||showSnapshot)return;const id=crypto.randomUUID(),copy={...selected,id,position:{x:(selected.position?.x||0)+40,y:(selected.position?.y||0)+40},data:{...selected.data,label:`${selected.data.label} copy`,status:'idle'}};setNodes(ns=>[...ns,copy]);setSelected(copy)};
 const removeSelected=()=>{if(!canEdit||showSnapshot)return;const ids=new Set(nodes.filter(n=>n.selected||n.id===selected?.id).map(n=>n.id));if(ids.size>1&&!window.confirm(`Delete ${ids.size} selected nodes and their connections?`))return;setNodes(ns=>ns.filter(n=>!ids.has(n.id)));setEdges(es=>es.filter(e=>!e.selected&&!ids.has(e.source)&&!ids.has(e.target)));setSelected(null)};
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(!canEdit||showSnapshot)return;const tag=(e.target as HTMLElement)?.tagName;if(['INPUT','TEXTAREA','SELECT'].includes(tag))return;const mod=e.ctrlKey||e.metaKey;if(mod&&e.key.toLowerCase()==='s'){e.preventDefault();void save().catch(()=>{});return}if(mod&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();return}if(mod&&e.key.toLowerCase()==='y'){e.preventDefault();redo();return}if(mod&&e.key.toLowerCase()==='d'){e.preventDefault();duplicateSelected();return}if(mod&&e.key.toLowerCase()==='c'&&selected){e.preventDefault();const copied=nodes.filter(n=>n.selected||n.id===selected.id);const ids=new Set(copied.map(n=>n.id));clipboard.current=structuredClone({nodes:copied,edges:edges.filter(edge=>ids.has(edge.source)&&ids.has(edge.target))});return}if(mod&&e.key.toLowerCase()==='v'&&clipboard.current){e.preventDefault();const ids=new Map<string,string>(clipboard.current.nodes.map((n:any)=>[n.id,crypto.randomUUID()]));const copies=clipboard.current.nodes.map((n:any)=>({...n,id:ids.get(n.id),selected:true,position:{x:n.position.x+50,y:n.position.y+50},data:{...n.data,status:'idle'}}));const links=clipboard.current.edges.map((edge:any)=>({...edge,id:crypto.randomUUID(),source:ids.get(edge.source),target:ids.get(edge.target)}));setNodes(ns=>[...ns.map(n=>({...n,selected:false})),...copies]);setEdges(es=>[...es,...links]);setSelected(copies[0]||null);return}if((e.key==='Delete'||e.key==='Backspace')){e.preventDefault();removeSelected()}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[selected,nodes,edges]);
 const run=async()=>{if(running)return;const invalid=validateLocal();if(invalid){setValidationError(invalid);setNotice(`Fix: ${invalid}`);return}let payload:any={};try{payload=JSON.parse(testPayload||'{}');setPayloadError('')}catch{setPayloadError('Test input must be valid JSON');return}setShowTest(false);setRunning(true);setRunMeta(null);setLogs([]);setNodes(ns=>ns.map(n=>({...n,data:{...n.data,status:'idle'}})));setEdges(es=>es.map(e=>({...e,animated:false,className:''})));try{if(canEdit)await save();const r=await sb<any>(`/workflows/${workflowId}/run`,{method:'POST',body:JSON.stringify({triggerType:'manual',payload})});let terminal=false;while(!terminal){await new Promise(x=>setTimeout(x,700));const current=await sb<any>(`/runs/${r.id}`);setRunMeta(current);setLogs((current.logs||[]).map((x:any)=>x.message));const states=new Map<string,string>((current.steps||[]).map((s:any)=>[String(s.nodeId),String(s.status)] as [string,string]));setNodes(ns=>ns.map(n=>{const s=states.get(String(n.id));return {...n,data:{...n.data,status:s==='RUNNING'?'running':s==='SUCCEEDED'?'done':s==='FAILED'?'failed':s==='WAITING'?'waiting':s==='SKIPPED'?'skipped':'idle'}}}));setEdges(es=>es.map(e=>{const a=states.get(String(e.source)),b=states.get(String(e.target));const hot=a==='RUNNING'||b==='RUNNING';const done=a==='SUCCEEDED'&&b==='SUCCEEDED';return {...e,animated:hot,className:hot?'n8n-edge-hot':done?'n8n-edge-done':''}}));terminal=['SUCCEEDED','FAILED','WAITING','CANCELLED'].includes(current.status);setNotice(current.status)}}catch(e:any){setNotice(e.message||'Run failed');setLogs(l=>[...l,e.message||'Run failed'])}finally{setRunning(false);void loadHistory()}};
 const inspectRun=async(id:string)=>{try{const current=await sb<any>(`/runs/${id}`);setShowSnapshot(true);setRunMeta(current);setLogs((current.logs||[]).map((x:any)=>x.message));const states=new Map((current.steps||[]).map((step:any)=>[step.nodeId,step.status]));setNodes(ns=>ns.map(n=>({...n,data:{...n.data,status:states.get(n.id)==='SUCCEEDED'?'done':states.get(n.id)==='FAILED'?'failed':states.get(n.id)==='RUNNING'?'running':'idle'}})));setShowHistory(false)}catch(error){setNotice(error instanceof Error?error.message:'Could not load run')}};
 const runAction=async(action:string)=>{if(!runMeta)return;try{const result=await sb<any>(`/runs/${runMeta.id}/${action}`,{method:'POST',body:'{}'});await inspectRun(result.runId||runMeta.id)}catch(error){setNotice(error instanceof Error?error.message:'Action failed')}};
 useEffect(()=>{if(!runMeta||!['RUNNING','QUEUED'].includes(runMeta.status)||running)return;const timer=setTimeout(()=>void inspectRun(runMeta.id),1000);return()=>clearTimeout(timer)},[runMeta,running]);
 const updateSelected=(patch:Record<string,any>)=>{if(!selected)return;const data={...selected.data,...patch};const next={...selected,data};setSelected(next);setNodes(ns=>ns.map(n=>n.id===selected.id?{...n,data}:n))};
 const visibleDefinition=showSnapshot?runMeta?.context?.definitionSnapshot:null;const visibleNodes=visibleDefinition?visibleDefinition.nodes.map((n:any)=>{const step=(runMeta?.steps||[]).filter((s:any)=>s.nodeId===n.id).at(-1);return {...n,type:'custom',data:{...n.data,status:step?.status==='SUCCEEDED'?'done':step?.status==='FAILED'?'failed':step?.status==='WAITING'?'waiting':step?.status==='RUNNING'?'running':step?.status==='SKIPPED'?'skipped':'idle'}}}):nodes.map(n=>({...n,data:{...n.data,warnings:Object.values(fieldErrors[n.id]||{})}}));
 const visibleEdges=visibleDefinition?visibleDefinition.edges.map((edge:any)=>{const outcomes=runMeta?.context?.outcomes||{};const source=outcomes[edge.source],target=outcomes[edge.target];const active=source?.status==='SUCCEEDED'&&target?.status==='SUCCEEDED'&&(edge.data?.when===undefined||String(edge.data.when)===String(source.route));return {...edge,label:edge.data?.when===undefined?undefined:String(edge.data.when).toUpperCase(),className:active?'n8n-edge-done':'',markerEnd:{type:MarkerType.ArrowClosed}}}):edges;
 const filtered=nodeLibrary.filter(n=>`${n[1]} ${n[2]}`.toLowerCase().includes(query.toLowerCase()));
 const total=Math.max(nodes.length,1),steps=runMeta?.steps||[],complete=steps.filter((s:any)=>['SUCCEEDED','FAILED','SKIPPED'].includes(s.status)).length,progress=runMeta?Math.round(complete/total*100):0;const selectedStep=selected&&steps.filter((s:any)=>s.nodeId===selected.id).at(-1);
 return <div className="n8n-shell">
  <header className="n8n-top"><button aria-label="Back" className="n8n-back" onClick={()=>window.history.back()}><ArrowLeft size={16}/></button><span className="n8n-node-icon"><Workflow size={16}/></span><div className="n8n-title"><b>{workflow?.name||'Workflow'}</b><small>{workflow?.status||'DRAFT'} · {dirty?'Unsaved changes':notice}</small></div><div className="n8n-toolbar" role="toolbar" aria-label="Workflow actions"><div className="editor-history-actions"><button onClick={undo} disabled={!canEdit||showSnapshot||historyIndex.current<=0} title="Undo (Ctrl+Z)"><Undo2 size={14}/></button><button onClick={redo} disabled={!canEdit||showSnapshot||historyIndex.current>=history.current.length-1} title="Redo (Ctrl+Y)"><Redo2 size={14}/></button>{selected&&<button onClick={duplicateSelected} title="Duplicate node (Ctrl+D)"><CopyPlus size={14}/></button>}</div><button className="n8n-btn" disabled={!canEdit||showSnapshot} onClick={()=>{const depths=new Map<string,number>();let pending=[...nodes];for(let wave=0;pending.length&&wave<nodes.length;wave++){const next=pending.filter(n=>edges.filter(e=>e.target===n.id).every(e=>depths.has(e.source)));for(const n of next)depths.set(n.id,wave);pending=pending.filter(n=>!depths.has(n.id))}const rows=new Map<number,number>();setNodes(ns=>ns.map(n=>{const level=depths.get(n.id)||0,row=rows.get(level)||0;rows.set(level,row+1);return {...n,position:{x:100+level*300,y:100+row*180}}}));setTimeout(()=>flow?.fitView({padding:.2}),50)}}>Auto layout</button><button className="n8n-btn" onClick={()=>flow?.fitView({nodes:nodes.filter(n=>n.selected),padding:.3})}>Zoom selection</button><div className="n8n-spacer"/><button className="n8n-btn" onClick={()=>{setShowHistory(v=>!v);setSelected(null);setShowAdd(false);void loadHistory()}}><History size={14}/>Runs</button><span className={`n8n-status ${running?'live':''}`}><i/>{running?'Executing workflow':validationError?'Needs attention':'Editor ready'}</span><button className={`n8n-btn ${workflow?.status==='ACTIVE'?'active':''}`} disabled={!canEdit||showSnapshot} onClick={toggleActive}><Power size={14}/>{workflow?.status==='ACTIVE'?'Active':'Activate'}</button><button className="n8n-btn" disabled={!canEdit||showSnapshot} onClick={()=>void save().catch(()=>{})}><Save size={14}/>Save</button><button className="n8n-btn primary" onClick={()=>{const invalid=validateLocal();if(invalid){setValidationError(invalid);setNotice(`Fix: ${invalid}`);return}setShowTest(true);setSelected(null);setShowHistory(false)}} disabled={running||!canRun||showSnapshot}><Play size={14}/>{running?'Running…':'Execute'}</button></div></header>
  <main className="n8n-body">{showSnapshot&&<div className="snapshot-banner">Run snapshot · v{runMeta?.context?.workflowVersion}<button onClick={()=>{setShowSnapshot(false);setRunMeta(null);setSelected(null)}}>Back to editing</button></div>}{validationError&&<div className="validation-banner" role="alert">{validationError}</div>}<div ref={canvasRef} className="n8n-canvas" onDoubleClick={e=>{if(canEdit&&!showSnapshot&&(e.target as HTMLElement).classList.contains("react-flow__pane")){setPendingSource('');setPendingHandle(undefined);setShowAdd(true)}}}><ReactFlow onInit={setFlow} nodes={visibleNodes} edges={visibleEdges} nodesDraggable={canEdit&&!showSnapshot} nodesConnectable={canEdit&&!showSnapshot} onNodesChange={showSnapshot?undefined:onNodesChange} onEdgesChange={showSnapshot?undefined:onEdgesChange} onConnect={canEdit&&!showSnapshot?onConnect:undefined} onNodeClick={(_,n)=>{setSelected(n);setShowAdd(false);setShowTest(false);setShowHistory(false)}} onPaneClick={()=>setSelected(null)} zoomOnDoubleClick={false} nodeTypes={nodeTypes} fitView fitViewOptions={{padding:.25,maxZoom:1}} minZoom={.1} snapToGrid snapGrid={[20,20]} selectionOnDrag multiSelectionKeyCode="Shift" deleteKeyCode={null} defaultEdgeOptions={{markerEnd:{type:MarkerType.ArrowClosed}}}><Background gap={20} size={1}/><MiniMap/><Controls/></ReactFlow>{nodes.length===0&&<div className="n8n-empty-hint"><div><Plus size={24}/></div><b>Start your workflow</b><small>Add your first node and connect the steps.</small></div>}</div>
  {canEdit&&!showSnapshot&&!selected&&!showTest&&!showHistory&&<button className="n8n-fab" onClick={()=>{setPendingSource('');setPendingHandle(undefined);setShowAdd(v=>!v)}} aria-label="Add node"><Plus size={23}/></button>}
  {showAdd&&!selected&&<aside className="n8n-add-panel"><div className="n8n-panel-head"><b>{pendingSource?'Add next node':'Add a node'}</b><button aria-label="Close panel" className="n8n-icon-btn" onClick={()=>{setShowAdd(false);setPendingSource('')}}><X size={15}/></button></div><div className="n8n-search"><Search size={14}/><input aria-label="Search nodes" autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search nodes…"/></div><div className="n8n-node-options">{filtered.map(([kind,label,cat,Icon])=><button className="n8n-node-option" key={kind} onClick={()=>addNode(kind,label)}><Icon size={17}/><b>{label}</b><small>{cat}</small></button>)}</div></aside>}
  {selected&&<aside className="n8n-inspector"><div className="n8n-inspector-header"><span><b>{selected.data.label}</b><small>{String(selected.data.kind).toUpperCase()} NODE</small></span><button aria-label="Close panel" className="n8n-icon-btn" onClick={()=>setSelected(null)}><X size={15}/></button></div><div className="n8n-inspector-body"><fieldset disabled={!canEdit||showSnapshot} style={{border:0,padding:0,margin:0}}>{fieldErrors[selected.id]&&<ul role="alert" className="inline-error">{Object.entries(fieldErrors[selected.id]).map(([field,message])=><li key={field}>{field}: {message}</li>)}</ul>}<Field label="Display name"><input value={selected.data.label||''} onChange={e=>updateSelected({label:e.target.value})}/></Field>{selected.data.kind==='trigger'&&<PayloadEditor value={testPayload} onChange={setTestPayload}/>}<ConfigFields node={selected} credentials={credentials} update={config=>updateSelected({config})}/><RequestFields key={selected.id} kind={selected.data.kind} config={selected.data.config||{}} onChange={config=>updateSelected({config})}/>{['webhook','schedule'].includes(selected.data.kind)&&workflow&&<TriggerConfig onInspectRun={id=>void inspectRun(id)} beforeSave={()=>save()} workflowId={workflowId} slug={workflow.slug} nodeId={selected.id} kind={selected.data.kind} config={selected.data.config||{}}/>}<div className="n8n-two"><Field label="Retry"><select value={selected.data.retry||0} onChange={e=>updateSelected({retry:Number(e.target.value)})}><option value="0">None</option><option value="1">1</option><option value="3">3</option><option value="5">5</option></select></Field><Field label="On failure"><select value={selected.data.continueOnFailure?'continue':'stop'} onChange={e=>updateSelected({continueOnFailure:e.target.value==='continue'})}><option value="stop">Stop workflow</option><option value="continue">Continue</option></select></Field></div></fieldset>{selectedStep&&<div className="execution-card"><div className="execution-title"><Activity size={14}/><b>Latest execution</b><span>{selectedStep.status}</span></div>{selectedStep.error&&<p className="execution-error">{selectedStep.error}</p>}<small>Attempt {selectedStep.attempt} · {selectedStep.startedAt?new Date(selectedStep.startedAt).toLocaleString():'Not started'} · {selectedStep.finishedAt&&selectedStep.startedAt?`${new Date(selectedStep.finishedAt).getTime()-new Date(selectedStep.startedAt).getTime()} ms`:'In progress'}</small><small>INPUT</small><pre>{JSON.stringify(selectedStep.input,null,2)}</pre><small>OUTPUT</small><pre>{JSON.stringify(selectedStep.output,null,2)}</pre></div>}<div className="node-actions" hidden={!canEdit||showSnapshot}><button className="n8n-btn" onClick={duplicateSelected}><CopyPlus size={13}/>Duplicate</button><button className="n8n-btn danger-wide" onClick={removeSelected}><Trash2 size={13}/>Delete</button></div></div></aside>}
  {showTest&&<aside className="n8n-inspector"><div className="n8n-inspector-header"><span><b>Test workflow</b><small>MANUAL TRIGGER INPUT</small></span><button aria-label="Close panel" className="n8n-icon-btn" onClick={()=>setShowTest(false)}><X size={15}/></button></div><div className="n8n-inspector-body"><p className="node-help">This JSON becomes <code>trigger</code> for the workflow. Templates such as <code>{'{{trigger.email}}'}</code> resolve from it.</p><PayloadEditor value={testPayload} onChange={setTestPayload}/>{payloadError&&<div className="inline-error">{payloadError}</div>}<button className="n8n-btn primary run-wide" onClick={run}><Play size={14}/>Run workflow</button></div></aside>}
  {showHistory&&<aside className="n8n-inspector"><div className="n8n-inspector-header"><span><b>Execution history</b><small>THIS WORKFLOW</small></span><button aria-label="Close panel" className="n8n-icon-btn" onClick={()=>setShowHistory(false)}><X size={15}/></button></div><div className="history-list">{historyRuns.map(r=><button key={r.id} onClick={()=>void inspectRun(r.id)} className="history-row"><span className={`run-dot ${String(r.status).toLowerCase()}`}/><span><b>{r.status}</b><small>{new Date(r.createdAt).toLocaleString()}</small></span><ArrowLeft size={13} className="history-arrow"/></button>)}{historyRuns.length>=50&&<button className="n8n-btn" onClick={()=>void sb<any[]>(`/runs?workflowId=${workflowId}&cursor=${historyRuns.at(-1)?.id}`).then(rows=>setHistoryRuns(old=>[...old,...rows.filter(r=>!old.some(x=>x.id===r.id))]))}>Load more</button>}{!historyRuns.length&&<div className="n8n-empty-hint small"><b>No runs yet</b></div>}</div></aside>}
  {(running||runMeta)&&<div className="n8n-runbar"><span><b>{runMeta?.status||'QUEUED'}</b><small>{logs.at(-1)||'Starting execution…'}</small></span><div className="progress"><span style={{width:`${progress}%`}}/></div><b>{Math.min(100,progress)}%</b>{runMeta?.status==='WAITING'&&<><button className="n8n-btn" onClick={()=>void runAction('approve')}>Approve</button><button className="n8n-btn" onClick={()=>void runAction('reject')}>Reject</button></>}{runMeta&&['RUNNING','QUEUED','WAITING'].includes(runMeta.status)&&<button className="n8n-btn" onClick={()=>void runAction('cancel')}>Cancel</button>}{runMeta&&['FAILED','CANCELLED'].includes(runMeta.status)&&<button className="n8n-btn" onClick={()=>void runAction('retry')}>Retry snapshot</button>}<details><summary>Logs ({logs.length})</summary><pre>{logs.join('\n')}</pre></details></div>}
  </main>
 </div>
}
