'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {ReactFlow,Background,Controls,MiniMap,addEdge,useNodesState,useEdgesState,Handle,Position,MarkerType,NodeProps} from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import './n8n-builder.css';
import {Activity,ArrowLeft,CheckCircle2,Clock3,Database,GitBranch,Globe2,Mail,Plus,Save,Search,Settings2,ShieldCheck,Sparkles,Terminal,Users,Webhook,Zap,Play,Power,X,Workflow,Braces,History,Trash2} from 'lucide-react';
import {sb} from '../lib/switchboard';

type RunState='idle'|'running'|'done'|'failed';
type NodeData={label:string;kind:string;subtitle?:string;status?:RunState;config?:Record<string,any>;retry?:number;continueOnFailure?:boolean};
const nodeLibrary=[['trigger','Manual Trigger','Input',Zap],['http','HTTP Request','Integration',Globe2],['postgres','PostgreSQL','Data',Database],['webhook','Webhook','Input',Webhook],['ssh','SSH Action','Systems',Terminal],['powershell','PowerShell','Systems',Terminal],['email','Send Email','Messaging',Mail],['approval','Approval','Control',Clock3],['condition','Condition','Logic',GitBranch],['delay','Delay','Control',Clock3],['createUser','Create User','Directory',Users],['disableUser','Disable User','Directory',Users],['addGroup','Add Group','Access',ShieldCheck],['assignLicense','Assign License','Access',Sparkles],['health','Health Check','Monitoring',Activity]] as const;
const icons:any={trigger:Zap,http:Globe2,postgres:Database,webhook:Webhook,ssh:Terminal,powershell:Terminal,email:Mail,approval:Clock3,condition:GitBranch,delay:Clock3,createUser:Users,disableUser:Users,addGroup:ShieldCheck,assignLicense:Sparkles,health:Activity};
const defaults=(kind:string)=>kind==='delay'?{ms:1000}:kind==='health'?{url:'https://switchboard-api-tqc3.onrender.com/health',timeoutMs:8000}:kind==='http'?{method:'GET',url:'https://switchboard-api-tqc3.onrender.com/health',timeoutMs:15000}:kind==='condition'?{field:'trigger.department',operator:'equals',value:'IT'}:kind==='createUser'?{email:'{{trigger.email}}',fullName:'{{trigger.fullName}}',department:'{{trigger.department}}'}:kind==='disableUser'?{email:'{{trigger.email}}'}:kind==='addGroup'?{email:'{{trigger.email}}',group:'Employees'}:kind==='assignLicense'?{email:'{{trigger.email}}',license:'Standard'}:kind==='email'?{to:'{{trigger.email}}',subject:'Welcome',text:'Welcome to the team'}:{};

function FlowNode({data,selected}:NodeProps){const d=data as NodeData;const Icon=icons[d.kind]||Zap;const condition=d.kind==='condition';return <div className={`n8n-node ${selected?'selected':''} ${d.status||''}`}><Handle type="target" position={Position.Left}/><div className="n8n-node-top"><span className="n8n-node-icon"><Icon size={16}/></span><span><b>{d.label}</b><small>{d.kind}</small></span>{d.status==='running'?<Activity size={14} className="spin"/>:d.status==='done'?<CheckCircle2 size={14}/>:null}</div><div className="n8n-node-body">{d.status==='running'?'Executing…':d.status==='done'?'Execution complete':d.status==='failed'?'Execution failed':d.subtitle||'Click to configure'}</div>{condition?<><Handle id="true" className="condition-handle true" type="source" position={Position.Right} style={{top:'38%'}}/><Handle id="false" className="condition-handle false" type="source" position={Position.Right} style={{top:'72%'}}/><span className="branch-label true">TRUE</span><span className="branch-label false">FALSE</span></>:<Handle type="source" position={Position.Right}/>}</div>}

function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="n8n-field"><span>{label}</span>{children}</label>}
function ConfigFields({node,credentials,update}:{node:any;credentials:any[];update:(config:any)=>void}){const kind=String(node.data.kind),c=node.data.config||{};const set=(key:string,value:any)=>update({...c,[key]:value});const cred=<Field label="Credential"><select value={c.credentialRef||''} onChange={e=>set('credentialRef',e.target.value||undefined)}><option value="">No saved credential</option>{credentials.map(x=><option key={x.id} value={x.id}>{x.name} · {x.type}</option>)}</select></Field>;
 if(kind==='trigger'||kind==='webhook'||kind==='approval')return <p className="node-help">{kind==='trigger'?'Input is provided when you execute the workflow.':kind==='webhook'?'Webhook payload becomes the trigger input.':'Execution pauses here until an operator approves or rejects the run.'}</p>;
 if(kind==='delay')return <Field label="Delay (milliseconds)"><input type="number" min="0" max="30000" value={c.ms??1000} onChange={e=>set('ms',Number(e.target.value))}/></Field>;
 if(kind==='health')return <><Field label="Health URL"><input value={c.url||''} onChange={e=>set('url',e.target.value)} placeholder="https://service/health"/></Field><Field label="Timeout (ms)"><input type="number" value={c.timeoutMs??8000} onChange={e=>set('timeoutMs',Number(e.target.value))}/></Field></>;
 if(kind==='http')return <><Field label="Method"><select value={c.method||'GET'} onChange={e=>set('method',e.target.value)}><option>GET</option><option>POST</option><option>PUT</option><option>PATCH</option><option>DELETE</option></select></Field><Field label="URL"><input value={c.url||''} onChange={e=>set('url',e.target.value)} placeholder="https://api.example.com"/></Field><Field label="Timeout (ms)"><input type="number" value={c.timeoutMs??15000} onChange={e=>set('timeoutMs',Number(e.target.value))}/></Field></>;
 if(kind==='condition')return <><Field label="Field"><input value={c.field||''} onChange={e=>set('field',e.target.value)} placeholder="trigger.department"/></Field><Field label="Operator"><select value={c.operator||'equals'} onChange={e=>set('operator',e.target.value)}><option value="equals">Equals</option><option value="contains">Contains</option><option value="exists">Exists</option><option value="truthy">Truthy</option></select></Field><Field label="Expected value"><input value={c.value??''} onChange={e=>set('value',e.target.value)}/></Field><div className="branch-help"><span><i className="branch-dot true"/>TRUE output</span><span><i className="branch-dot false"/>FALSE output</span></div></>;
 if(kind==='postgres')return <>{cred}<Field label="Connection string"><input value={c.connectionString||''} onChange={e=>set('connectionString',e.target.value)} placeholder="Or use a credential above"/></Field><Field label="SQL query"><textarea value={c.query||''} onChange={e=>set('query',e.target.value)} placeholder="select now();"/></Field></>;
 if(kind==='ssh'||kind==='powershell')return <>{cred}<Field label="Host"><input value={c.host||''} onChange={e=>set('host',e.target.value)}/></Field><Field label="Username"><input value={c.username||''} onChange={e=>set('username',e.target.value)}/></Field><Field label="Command"><textarea value={c.command||''} onChange={e=>set('command',e.target.value)} placeholder={kind==='powershell'?'Get-Service':'uname -a'}/></Field></>;
 if(kind==='email')return <>{cred}<Field label="To"><input value={c.to||''} onChange={e=>set('to',e.target.value)} placeholder="{{trigger.email}}"/></Field><Field label="Subject"><input value={c.subject||''} onChange={e=>set('subject',e.target.value)}/></Field><Field label="Message"><textarea value={c.text||''} onChange={e=>set('text',e.target.value)}/></Field></>;
 if(kind==='createUser')return <><Field label="Email"><input value={c.email||''} onChange={e=>set('email',e.target.value)} placeholder="{{trigger.email}}"/></Field><Field label="Full name"><input value={c.fullName||''} onChange={e=>set('fullName',e.target.value)} placeholder="{{trigger.fullName}}"/></Field><Field label="Department"><input value={c.department||''} onChange={e=>set('department',e.target.value)}/></Field><Field label="Title"><input value={c.title||''} onChange={e=>set('title',e.target.value)}/></Field></>;
 if(kind==='disableUser'||kind==='addGroup'||kind==='assignLicense')return <><Field label="User email"><input value={c.email||''} onChange={e=>set('email',e.target.value)} placeholder="{{trigger.email}}"/></Field>{kind==='addGroup'&&<Field label="Group"><input value={c.group||''} onChange={e=>set('group',e.target.value)}/></Field>}{kind==='assignLicense'&&<Field label="License"><input value={c.license||''} onChange={e=>set('license',e.target.value)}/></Field>}</>;
 return <Field label="Configuration JSON"><textarea value={JSON.stringify(c,null,2)} readOnly/></Field>;
}

export function BuilderClient({workflowId}:{workflowId:string}){
 const [nodes,setNodes,onNodesChange]=useNodesState<any>([]),[edges,setEdges,onEdgesChange]=useEdgesState<any>([]);
 const [workflow,setWorkflow]=useState<any>(null),[selected,setSelected]=useState<any>(null),[query,setQuery]=useState(''),[showAdd,setShowAdd]=useState(false),[logs,setLogs]=useState<string[]>([]),[running,setRunning]=useState(false),[notice,setNotice]=useState('Loading…'),[runMeta,setRunMeta]=useState<any>(null),[credentials,setCredentials]=useState<any[]>([]),[showTest,setShowTest]=useState(false),[testPayload,setTestPayload]=useState('{\n  "email": "test@example.com",\n  "fullName": "Test User",\n  "department": "IT"\n}'),[payloadError,setPayloadError]=useState(''),[showHistory,setShowHistory]=useState(false),[historyRuns,setHistoryRuns]=useState<any[]>([]);
 const nodeTypes=useMemo(()=>({custom:FlowNode}),[]);
 useEffect(()=>{sb<any>(`/workflows/${workflowId}`).then(w=>{setWorkflow(w);const def=w.definition||{};setNodes((def.nodes||[]).map((n:any)=>({...n,type:'custom',data:{...n.data,status:'idle',config:{...defaults(n.data?.kind),...(n.data?.config||{})}}})));setEdges((def.edges||[]).map((e:any,i:number)=>({...e,id:e.id||`edge-${e.source}-${e.target}-${i}`,animated:false,markerEnd:{type:MarkerType.ArrowClosed},label:e.data?.when===undefined?undefined:String(e.data.when).toUpperCase()})));setNotice('Saved')}).catch(e=>setNotice(e.message));sb<any[]>('/credentials').then(setCredentials).catch(()=>{})},[workflowId,setNodes,setEdges]);
 const loadHistory=async()=>{try{setHistoryRuns(await sb<any[]>(`/runs?workflowId=${workflowId}`))}catch{}};
 const onConnect=useCallback((p:any)=>setEdges(es=>{const source=nodes.find(n=>n.id===p.source);const when=source?.data?.kind==='condition'&&p.sourceHandle?String(p.sourceHandle):undefined;return addEdge({...p,id:`edge-${crypto.randomUUID()}`,data:when?{when}:undefined,label:when?.toUpperCase(),animated:false,markerEnd:{type:MarkerType.ArrowClosed}},es)}),[setEdges,nodes]);
 const definition=()=>({nodes:nodes.map(n=>({id:String(n.id),type:'custom',position:{x:Number(n.position?.x||0),y:Number(n.position?.y||0)},data:{...n.data,status:undefined,config:{...defaults(String(n.data?.kind||'')),...(n.data?.config||{})}}})),edges:edges.map((e:any,i:number)=>({id:String(e.id||`edge-${e.source}-${e.target}-${i}`),source:String(e.source),target:String(e.target),...(e.sourceHandle?{sourceHandle:String(e.sourceHandle)}:{}),...(e.data?{data:e.data}:{})}))});
 const save=async()=>{setNotice('Saving…');try{const w=await sb<any>(`/workflows/${workflowId}`,{method:'PUT',body:JSON.stringify({definition:definition()})});setWorkflow(w);setNotice(`Saved · v${w.version}`);return w}catch(e:any){setNotice(e.message||'Save failed');throw e}};
 const toggleActive=async()=>{if(!workflow)return;const status=workflow.status==='ACTIVE'?'DRAFT':'ACTIVE';setNotice('Updating…');try{await save();const w=await sb<any>(`/workflows/${workflowId}`,{method:'PUT',body:JSON.stringify({status})});setWorkflow(w);setNotice(status==='ACTIVE'?'Active':'Draft')}catch(e:any){setNotice(e.message||'Update failed')}};
 const addNode=(kind:string,label:string)=>{const i=nodes.length;setNodes(ns=>[...ns,{id:crypto.randomUUID(),type:'custom',position:{x:250+(i%4)*250,y:140+Math.floor(i/4)*180},data:{label,kind,subtitle:'Ready to configure',status:'idle',config:defaults(kind),retry:0}}]);setShowAdd(false)};
 const run=async()=>{if(running)return;let payload:any={};try{payload=JSON.parse(testPayload||'{}');setPayloadError('')}catch{setPayloadError('Test input must be valid JSON');return}setShowTest(false);setRunning(true);setRunMeta(null);setLogs([]);setNodes(ns=>ns.map(n=>({...n,data:{...n.data,status:'idle'}})));setEdges(es=>es.map(e=>({...e,animated:false,className:''})));try{await save();const r=await sb<any>(`/workflows/${workflowId}/run`,{method:'POST',body:JSON.stringify({triggerType:'manual',payload})});let terminal=false;while(!terminal){await new Promise(x=>setTimeout(x,700));const current=await sb<any>(`/runs/${r.id}`);setRunMeta(current);setLogs((current.logs||[]).map((x:any)=>x.message));const states=new Map<string,string>((current.steps||[]).map((s:any)=>[String(s.nodeId),String(s.status)] as [string,string]));setNodes(ns=>ns.map(n=>{const s=states.get(String(n.id));return {...n,data:{...n.data,status:s==='RUNNING'?'running':s==='SUCCEEDED'?'done':s==='FAILED'?'failed':'idle'}}}));setEdges(es=>es.map(e=>{const a=states.get(String(e.source)),b=states.get(String(e.target));const hot=a==='RUNNING'||b==='RUNNING';const done=a==='SUCCEEDED'&&b==='SUCCEEDED';return {...e,animated:hot,className:hot?'n8n-edge-hot':done?'n8n-edge-done':''}}));terminal=['SUCCEEDED','FAILED','WAITING','CANCELLED'].includes(current.status);setNotice(current.status)}}catch(e:any){setNotice(e.message||'Run failed');setLogs(l=>[...l,e.message||'Run failed'])}finally{setRunning(false);void loadHistory()}};
 const updateSelected=(patch:Record<string,any>)=>{if(!selected)return;const data={...selected.data,...patch};const next={...selected,data};setSelected(next);setNodes(ns=>ns.map(n=>n.id===selected.id?next:n))};
 const filtered=nodeLibrary.filter(n=>`${n[1]} ${n[2]}`.toLowerCase().includes(query.toLowerCase()));
 const total=Math.max(nodes.length,1),steps=runMeta?.steps||[],complete=steps.filter((s:any)=>['SUCCEEDED','FAILED','SKIPPED'].includes(s.status)).length,progress=runMeta?Math.round(complete/total*100):0;const selectedStep=selected&&steps.filter((s:any)=>s.nodeId===selected.id).at(-1);
 return <div className="n8n-shell">
  <header className="n8n-top"><button className="n8n-back" onClick={()=>history.back()}><ArrowLeft size={16}/></button><span className="n8n-node-icon"><Workflow size={16}/></span><div className="n8n-title"><b>{workflow?.name||'Workflow'}</b><small>{workflow?.status||'DRAFT'} · {notice}</small></div><div className="n8n-spacer"/><button className="n8n-btn" onClick={()=>{setShowHistory(v=>!v);setSelected(null);setShowAdd(false);void loadHistory()}}><History size={14}/>Runs</button><span className={`n8n-status ${running?'live':''}`}><i/>{running?'Executing workflow':'Editor ready'}</span><button className={`n8n-btn ${workflow?.status==='ACTIVE'?'active':''}`} onClick={toggleActive}><Power size={14}/>{workflow?.status==='ACTIVE'?'Active':'Activate'}</button><button className="n8n-btn" onClick={save}><Save size={14}/>Save</button><button className="n8n-btn primary" onClick={()=>{setShowTest(true);setSelected(null);setShowHistory(false)}} disabled={running}><Play size={14}/>{running?'Running…':'Execute'}</button></header>
  <main className="n8n-body"><div className="n8n-canvas"><ReactFlow nodes={nodes} edges={edges} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} onConnect={onConnect} onNodeClick={(_,n)=>{setSelected(n);setShowAdd(false);setShowTest(false);setShowHistory(false)}} onPaneClick={()=>setSelected(null)} nodeTypes={nodeTypes} fitView defaultEdgeOptions={{markerEnd:{type:MarkerType.ArrowClosed}}}><Background gap={26} size={1}/><MiniMap/><Controls/></ReactFlow>{nodes.length===0&&<div className="n8n-empty-hint"><div><Plus size={24}/></div><b>Start your workflow</b><small>Add your first node and connect the steps.</small></div>}</div>
  {!selected&&!showTest&&!showHistory&&<button className="n8n-fab" onClick={()=>setShowAdd(v=>!v)} aria-label="Add node"><Plus size={23}/></button>}
  {showAdd&&!selected&&<aside className="n8n-add-panel"><div className="n8n-panel-head"><b>Add a node</b><button className="n8n-icon-btn" onClick={()=>setShowAdd(false)}><X size={15}/></button></div><div className="n8n-search"><Search size={14}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search nodes…"/></div><div className="n8n-node-options">{filtered.map(([kind,label,cat,Icon])=><button className="n8n-node-option" key={kind} onClick={()=>addNode(kind,label)}><Icon size={17}/><b>{label}</b><small>{cat}</small></button>)}</div></aside>}
  {selected&&<aside className="n8n-inspector"><div className="n8n-inspector-header"><span><b>{selected.data.label}</b><small>{String(selected.data.kind).toUpperCase()} NODE</small></span><button className="n8n-icon-btn" onClick={()=>setSelected(null)}><X size={15}/></button></div><div className="n8n-inspector-body"><Field label="Display name"><input value={selected.data.label||''} onChange={e=>updateSelected({label:e.target.value})}/></Field><ConfigFields node={selected} credentials={credentials} update={config=>updateSelected({config})}/><div className="n8n-two"><Field label="Retry"><select value={selected.data.retry||0} onChange={e=>updateSelected({retry:Number(e.target.value)})}><option value="0">None</option><option value="1">1</option><option value="3">3</option><option value="5">5</option></select></Field><Field label="On failure"><select value={selected.data.continueOnFailure?'continue':'stop'} onChange={e=>updateSelected({continueOnFailure:e.target.value==='continue'})}><option value="stop">Stop workflow</option><option value="continue">Continue</option></select></Field></div>{selectedStep&&<div className="execution-card"><div className="execution-title"><Activity size={14}/><b>Latest execution</b><span>{selectedStep.status}</span></div>{selectedStep.error&&<p className="execution-error">{selectedStep.error}</p>}<small>INPUT</small><pre>{JSON.stringify(selectedStep.input,null,2)}</pre><small>OUTPUT</small><pre>{JSON.stringify(selectedStep.output,null,2)}</pre></div>}<button className="n8n-btn danger-wide" onClick={()=>{setNodes(ns=>ns.filter(n=>n.id!==selected.id));setEdges(es=>es.filter(e=>e.source!==selected.id&&e.target!==selected.id));setSelected(null)}}><Trash2 size={13}/>Delete node</button></div></aside>}
  {showTest&&<aside className="n8n-inspector"><div className="n8n-inspector-header"><span><b>Test workflow</b><small>MANUAL TRIGGER INPUT</small></span><button className="n8n-icon-btn" onClick={()=>setShowTest(false)}><X size={15}/></button></div><div className="n8n-inspector-body"><p className="node-help">This JSON becomes <code>trigger</code> for the workflow. Templates such as <code>{'{{trigger.email}}'}</code> resolve from it.</p><Field label="Input JSON"><textarea className="payload-editor" value={testPayload} onChange={e=>setTestPayload(e.target.value)}/></Field>{payloadError&&<div className="inline-error">{payloadError}</div>}<button className="n8n-btn primary run-wide" onClick={run}><Play size={14}/>Run workflow</button></div></aside>}
  {showHistory&&<aside className="n8n-inspector"><div className="n8n-inspector-header"><span><b>Execution history</b><small>THIS WORKFLOW</small></span><button className="n8n-icon-btn" onClick={()=>setShowHistory(false)}><X size={15}/></button></div><div className="history-list">{historyRuns.slice(0,30).map(r=><a key={r.id} href={`/runs/${r.id}`} className="history-row"><span className={`run-dot ${String(r.status).toLowerCase()}`}/><span><b>{r.status}</b><small>{new Date(r.createdAt).toLocaleString()}</small></span><ArrowLeft size={13} className="history-arrow"/></a>)}{!historyRuns.length&&<div className="n8n-empty-hint small"><b>No runs yet</b></div>}</div></aside>}
  {(running||runMeta)&&<div className="n8n-runbar"><span><b>{runMeta?.status||'QUEUED'}</b><small>{logs.at(-1)||'Starting execution…'}</small></span><div className="progress"><span style={{width:`${progress}%`}}/></div><b>{progress}%</b></div>}
  </main>
 </div>
}
