'use client';
import Link from'next/link';
import {WorkflowDetails} from './WorkflowDetails';
import{ChangeEvent,useEffect,useRef,useState}from'react';
import{usePathname,useRouter}from'next/navigation';
import{LogOut,Activity,Archive,Copy,Download,FileUp,KeyRound,MoreHorizontal,Network,Plus,ScrollText,Settings,ShieldCheck,Sparkles,Trash2,Users,Workflow,Zap}from'lucide-react';
import{workflowTemplates}from'../lib/templates';
import{getSession,logoutSession}from'../lib/switchboard';
import{sb}from'../lib/switchboard';
const items=[{href:'/triggers',label:'Triggers',icon:Zap},{href:'/credentials',label:'Secrets',icon:KeyRound},{href:'/directory',label:'Directory',icon:Users},{href:'/audit',label:'Audit',icon:ScrollText},{href:'/users',label:'Users',icon:ShieldCheck},{href:'/settings',label:'System',icon:Settings}];
export function EditorRail(){const path=usePathname(),router=useRouter();const[error,setError]=useState('');const[editing,setEditing]=useState<any>(null);const[search,setSearch]=useState(''),[template,setTemplate]=useState(''),[open,setOpen]=useState(false),[rows,setRows]=useState<any[]>([]),[busy,setBusy]=useState('');const inputRef=useRef<HTMLInputElement>(null);const role=getSession()?.user?.role;const canCreate=role==='ADMIN'||role==='OPERATOR';const currentId=path.match(/^\/workflows\/([^/]+)/)?.[1];const load=()=>sb<any[]>('/workflows').then(setRows).catch(e=>setError(e.message));useEffect(()=>{void load()},[open,path]);
 async function createFrom(name:string,definition:any,description?:string){setBusy('new');try{const slug=(name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||`workflow-${Date.now()}`)+`-${Date.now().toString().slice(-5)}`;const w=await sb<any>('/workflows',{method:'POST',body:JSON.stringify({name,slug,status:'DRAFT',description:description||undefined,definition})});await load();router.push(`/workflows/${w.id}`);setOpen(false)}catch(e){setError(e instanceof Error?e.message:'Action failed');setOpen(true)}finally{setBusy('')}}
 async function create(){const name=prompt('Workflow name');if(!name)return;await createFrom(name,{nodes:[{id:'start',type:'custom',position:{x:180,y:220},data:{label:'Manual Trigger',kind:'trigger',config:{}}}],edges:[]})}
 async function createTemplate(){const chosen=workflowTemplates[Number(template||0)];await createFrom(chosen.name,chosen.definition)}
 async function importFile(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];e.target.value='';if(!file)return;try{const parsed=JSON.parse(await file.text());if(!parsed?.definition?.nodes||!Array.isArray(parsed.definition.nodes))throw new Error('Invalid SWITCHBOARD workflow file');await createFrom(parsed.name||file.name.replace(/\.[^.]+$/,''),parsed.definition,parsed.description)}catch(err:any){alert(err.message||'Could not import workflow')}}
 async function editDetails(w:any){try{setEditing(await sb(`/workflows/${w.id}`))}catch(e){alert(e instanceof Error?e.message:'Could not open details')}}
 async function duplicate(w:any){setBusy(w.id);try{const full=await sb<any>(`/workflows/${w.id}`);await createFrom(`${w.name} copy`,full.definition,full.description)}catch(e){setError(e instanceof Error?e.message:'Action failed');setOpen(true)}finally{setBusy('')}}
 async function archive(w:any){setBusy(w.id);try{const saved=await sb(`/workflows/${w.id}`,{method:'PUT',body:JSON.stringify({status:w.status==='ARCHIVED'?'DRAFT':'ARCHIVED'})});window.dispatchEvent(new CustomEvent('switchboard:workflow-meta',{detail:saved}));await load()}catch(e){setError(e instanceof Error?e.message:'Action failed');setOpen(true)}finally{setBusy('')}}
 async function remove(w:any){if(!confirm(`Delete ${w.name}? This also deletes its runs and triggers.`))return;setBusy(w.id);try{await sb(`/workflows/${w.id}`,{method:'DELETE'});const left=rows.filter(x=>x.id!==w.id);if(w.id===currentId)router.push(left[0]?`/workflows/${left[0].id}`:'/workflows');await load()}catch(e){setError(e instanceof Error?e.message:'Action failed');setOpen(true)}finally{setBusy('')}}
 async function exportWorkflow(w:any){const full=await sb<any>(`/workflows/${w.id}`);const blob=new Blob([JSON.stringify({name:full.name,description:full.description,status:'DRAFT',definition:full.definition},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${w.slug}.switchboard.json`;a.click();URL.revokeObjectURL(url)}
 return <>{editing&&<WorkflowDetails workflow={editing} onClose={()=>setEditing(null)} onSaved={saved=>{void load();window.dispatchEvent(new CustomEvent('switchboard:workflow-meta',{detail:saved}))}}/>}<aside className="editor-rail"><button className="editor-rail-brand" title="SWITCHBOARD" onClick={()=>setOpen(v=>!v)}><Network size={20}/></button><nav><button className="active" title="Workflows" onClick={()=>setOpen(v=>!v)}><Workflow size={18}/><span>Workflows</span></button>{items.map(({href,label,icon:Icon})=><Link key={href} href={href} title={label} aria-label={label}><Icon size={18}/><span>{label}</span></Link>)}</nav><button aria-label="Log out" className="editor-rail-logout" title="Log out" onClick={()=>void logoutSession().then(()=>router.replace('/login'))}><LogOut size={18}/></button></aside>{open&&<div className="workflow-switcher"><header><div><small>WORKSPACE</small><b>Workflows</b></div><div className="workflow-switcher-create"><button onClick={createTemplate} title="Start from template" disabled={!!busy||!canCreate}><Sparkles size={13}/></button><button onClick={()=>inputRef.current?.click()} title="Import workflow" disabled={!!busy||!canCreate}><FileUp size={13}/></button><button onClick={create} disabled={!!busy||!canCreate}><Plus size={14}/>New</button><input ref={inputRef} type="file" accept="application/json,.json" hidden onChange={importFile}/></div></header>{error&&<p role="alert" className="workflow-switcher-error">{error}</p>}<input aria-label="Search workflows" placeholder="Search workflows" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Workflow template" value={template} onChange={e=>setTemplate(e.target.value)}>{workflowTemplates.map((t,i)=><option key={t.name} value={i}>{t.name}</option>)}</select><div className="workflow-switcher-list">{rows.filter(w=>w.name.toLowerCase().includes(search.toLowerCase())).map(w=><div className={`workflow-switcher-row ${w.id===currentId?'current':''}`} key={w.id}><button className="workflow-switcher-main" onClick={()=>{router.push(`/workflows/${w.id}`);setOpen(false)}}><span><b>{w.name}</b><small>{w.status} · v{w.version}</small></span></button><details><summary title="Actions"><MoreHorizontal size={15}/></summary><div className="workflow-actions-pop"><button onClick={()=>editDetails(w)}>Edit details</button><button onClick={()=>duplicate(w)}><Copy size={12}/>Duplicate</button><button onClick={()=>exportWorkflow(w)}><Download size={12}/>Export</button><button onClick={()=>archive(w)}><Archive size={12}/>{w.status==='ARCHIVED'?'Restore':'Archive'}</button><button className="danger" onClick={()=>remove(w)}><Trash2 size={12}/>Delete</button></div></details></div>)}{!rows.length&&<div className="workflow-switcher-empty">No workflows yet.</div>}</div></div>}</>}
