'use client';
import {useState} from 'react';
export function KeyValueFields({label,value,onChange}:{label:string;value:Record<string,string>;onChange:(v:Record<string,string>)=>void}){
 const entries=Object.entries(value||{});
 return <fieldset className="n8n-field"><legend>{label}</legend>{entries.map(([key,v],i)=><div className="n8n-two" key={i}><input aria-label={`${label} key ${i+1}`} value={key} onChange={e=>onChange(Object.fromEntries(entries.map((row,j)=>j===i?[e.target.value,row[1]]:row)))}/><input aria-label={`${label} value ${i+1}`} value={v} onChange={e=>onChange({...value,[key]:e.target.value})}/><button aria-label={`Remove ${key}`} onClick={()=>onChange(Object.fromEntries(entries.filter((_,j)=>j!==i)))}>Remove</button></div>)}<button className="n8n-btn" onClick={()=>onChange({...value,[`key${entries.length+1}`]:''})}>Add {label.toLowerCase()}</button></fieldset>
}
export function RequestFields({kind,config,onChange}:{kind:string;config:Record<string,any>;onChange:(v:Record<string,any>)=>void}){
 const c=config,set=(key:string,value:unknown)=>onChange({...c,[key]:value});
 const field=(key:string,label:string,type='text')=><label className="n8n-field" key={key}><span>{label}</span><input type={type} value={c[key]??''} onChange={e=>set(key,type==='number'?Number(e.target.value):e.target.value)}/></label>;
 return <>{kind==='createUser'&&<KeyValueFields label="Custom fields" value={c.custom||{}} onChange={v=>set('custom',v)}/ >}{['http','health'].includes(kind)&&field('expectedStatus','Expected status','number')}{kind==='http'&&<><KeyValueFields label="Query parameters" value={c.queryParams||{}} onChange={v=>set('queryParams',v)}/><KeyValueFields label="Headers" value={c.headers||{}} onChange={v=>set('headers',v)}/><label className="n8n-field"><span>Body type</span><select value={c.bodyType||'json'} onChange={e=>set('bodyType',e.target.value)}><option value="json">JSON fields</option><option value="text">Text</option><option value="form">Form URL encoded</option></select></label>{c.bodyType==='text'?<label className="n8n-field"><span>Body</span><textarea value={c.body||''} onChange={e=>set('body',e.target.value)}/></label>:<KeyValueFields label="Body fields" value={typeof c.body==='object'?c.body:{}} onChange={v=>set('body',v)}/>}</>}{kind==='email'&&<>{field('cc','CC')}{field('bcc','BCC')}<label className="n8n-field"><span>HTML message</span><textarea value={c.html||''} onChange={e=>set('html',e.target.value)}/></label></>}{['ssh','powershell','postgres'].includes(kind)&&field('timeoutMs','Timeout (ms)','number')}{kind==='ssh'&&field('port','Port','number')}{kind==='postgres'&&<label className="n8n-field"><span>Query parameters (one per line)</span><textarea value={(c.params||[]).join('\n')} onChange={e=>set('params',e.target.value.split('\n'))}/></label>}{kind==='approval'&&<>{field('message','Approval message')}{field('approverEmail','Approver email (optional)','email')}{field('timeoutMinutes','Deadline in minutes (optional)','number')}<p>Execution fails if the deadline expires. Leave blank to wait for a decision.</p></>}</>;
}
