'use client';
import {useEffect,useState} from 'react';
import {sb} from '../lib/switchboard';
type Trigger={id:string;type:string;enabled:boolean;config:Record<string,unknown>};
type TriggerStatus={lastRun:{id:string;status:string;createdAt:string}|null;nextAt:string|null};
export function TriggerConfig({workflowId,slug,nodeId,kind,config,beforeSave,onInspectRun}:{workflowId:string;slug:string;nodeId:string;kind:string;config:Record<string,unknown>;beforeSave:()=>Promise<unknown>;onInspectRun:(id:string)=>void}){
 const [trigger,setTrigger]=useState<Trigger|null>(null),[secret,setSecret]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[status,setStatus]=useState<TriggerStatus|null>(null);
 const type=kind==='schedule'?'SCHEDULE':'WEBHOOK';
 useEffect(()=>{let valid=true;setSecret('');setTrigger(null);setStatus(null);sb<Trigger[]>(`/triggers/workflow/${workflowId}`).then(rows=>{if(valid)setTrigger(rows.find(t=>t.type===type&&t.config.nodeId===nodeId)||null)}).catch(e=>setMessage(e.message));return()=>{valid=false}},[workflowId,nodeId,type]);
 useEffect(()=>{if(!trigger)return;let valid=true;sb<TriggerStatus>(`/triggers/${trigger.id}/status`).then(result=>{if(valid)setStatus(result)}).catch(()=>{});return()=>{valid=false}},[trigger]);
 async function save(){setBusy(true);try{await beforeSave();const body={type,enabled:trigger?.enabled??true,config:{...config,nodeId}};const result=await sb<Trigger&{secret?:string}>(trigger?`/triggers/${trigger.id}`:`/triggers/workflow/${workflowId}`,{method:trigger?'PATCH':'POST',body:JSON.stringify(body)});setTrigger(result);if(result.secret)setSecret(result.secret);setMessage('Trigger saved. Activate the workflow to accept events.')}catch(e){setMessage(e instanceof Error?e.message:'Could not save trigger')}finally{setBusy(false)}}
 async function toggle(){if(!trigger)return;try{const result=await sb<Trigger>(`/triggers/${trigger.id}`,{method:'PATCH',body:JSON.stringify({enabled:!trigger.enabled})});setTrigger(result)}catch(e){setMessage(e instanceof Error?e.message:'Could not update trigger')}}
 async function rotate(){if(!trigger)return;try{const result=await sb<{secret:string}>(`/triggers/${trigger.id}/rotate-secret`,{method:'POST',body:'{}'});setSecret(result.secret);setMessage('Copy the new secret now. It is only returned once.')}catch(e){setMessage(e instanceof Error?e.message:'Could not rotate secret')}}
 async function testWebhook(){setBusy(true);try{const run=await sb<{runId:string}>(`/webhooks/${slug}`,{method:'POST',headers:{'x-switchboard-secret':secret},body:JSON.stringify({test:true,requestedAt:new Date().toISOString()})});setMessage('Webhook accepted and queued.');onInspectRun(run.runId)}catch(e){setMessage(e instanceof Error?e.message:'Webhook test failed')}finally{setBusy(false)}}
 async function copy(value:string){try{await navigator.clipboard.writeText(value);setMessage('Copied to clipboard.')}catch{setMessage('Clipboard access is unavailable. Select the value to copy it.')}}
 const url=`${process.env.NEXT_PUBLIC_WEBHOOK_BASE_URL||'https://switchboard-api-tqc3.onrender.com/api'}/webhooks/${slug}`;
 return <section className="execution-card"><b>{type==='SCHEDULE'?'Schedule':'Webhook'} trigger</b><p>{trigger?(trigger.enabled?'Enabled':'Disabled'):'Not registered'}</p><button className="n8n-btn" disabled={busy} onClick={()=>void save()}>{trigger?'Update configuration':'Register trigger'}</button>{trigger&&<button className="n8n-btn" onClick={()=>void toggle()}>{trigger.enabled?'Disable':'Enable'}</button>}{status?.nextAt&&<p>Next execution: {new Date(status.nextAt).toLocaleString()}</p>}{status?.lastRun&&<button className="n8n-btn" onClick={()=>onInspectRun(status.lastRun!.id)}>Latest run · {status.lastRun.status}</button>}{type==='WEBHOOK'&&<><label className="n8n-field"><span>Webhook URL</span><input readOnly value={url}/></label><button className="n8n-btn" onClick={()=>void copy(url)}>Copy URL</button><p>Send POST with the x-switchboard-secret header.</p>{trigger&&<button className="n8n-btn" onClick={()=>void rotate()}>Rotate secret</button>}<label className="n8n-field"><span>Webhook secret</span><input type="password" autoComplete="off" value={secret} onChange={e=>setSecret(e.target.value)} placeholder="Paste secret to test, or rotate above"/></label>{secret&&<button className="n8n-btn" onClick={()=>void copy(secret)}>Copy secret</button>}<button className="n8n-btn" disabled={!secret||!trigger?.enabled||busy} onClick={()=>void testWebhook()}>Send test webhook</button><p>The test sends an empty event with test and requestedAt fields. Configure downstream inputs before testing.</p></>}<p role="status">{message}</p></section>
}
