'use client';
import {useEffect,useState} from 'react';
import {sb} from '../lib/switchboard';
type Trigger={id:string;type:string;enabled:boolean;config:Record<string,unknown>};
export function TriggerConfig({workflowId,slug,nodeId,kind,config}:{workflowId:string;slug:string;nodeId:string;kind:string;config:Record<string,unknown>}){
 const [trigger,setTrigger]=useState<Trigger|null>(null),[secret,setSecret]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const type=kind==='schedule'?'SCHEDULE':'WEBHOOK';
 useEffect(()=>{let valid=true;setSecret('');setTrigger(null);sb<Trigger[]>(`/triggers/workflow/${workflowId}`).then(rows=>{if(valid)setTrigger(rows.find(t=>t.type===type&&t.config.nodeId===nodeId)||null)}).catch(e=>setMessage(e.message));return()=>{valid=false}},[workflowId,nodeId,type]);
 async function save(){setBusy(true);try{const body={type,enabled:true,config:{...config,nodeId}};const result=await sb<Trigger&{secret?:string}>(trigger?`/triggers/${trigger.id}`:`/triggers/workflow/${workflowId}`,{method:trigger?'PATCH':'POST',body:JSON.stringify(body)});setTrigger(result);if(result.secret)setSecret(result.secret);setMessage('Trigger saved. Activate the workflow to accept events.')}catch(e){setMessage(e instanceof Error?e.message:'Could not save trigger')}finally{setBusy(false)}}
 async function toggle(){if(!trigger)return;try{const result=await sb<Trigger>(`/triggers/${trigger.id}`,{method:'PATCH',body:JSON.stringify({enabled:!trigger.enabled})});setTrigger(result)}catch(e){setMessage(e instanceof Error?e.message:'Could not update trigger')}}
 async function rotate(){if(!trigger)return;try{const result=await sb<{secret:string}>(`/triggers/${trigger.id}/rotate-secret`,{method:'POST',body:'{}'});setSecret(result.secret)}catch(e){setMessage(e instanceof Error?e.message:'Could not rotate secret')}}
 const url=`${process.env.NEXT_PUBLIC_WEBHOOK_BASE_URL||'https://switchboard-api-tqc3.onrender.com/api'}/webhooks/${slug}`;
 return <section className="execution-card"><b>{type==='SCHEDULE'?'Schedule':'Webhook'} trigger</b><p>{trigger?(trigger.enabled?'Enabled':'Disabled'):'Not registered'}</p><button className="n8n-btn" disabled={busy} onClick={()=>void save()}>{trigger?'Update configuration':'Register trigger'}</button>{trigger&&<button className="n8n-btn" onClick={()=>void toggle()}>{trigger.enabled?'Disable':'Enable'}</button>}{type==='WEBHOOK'&&<><label className="n8n-field"><span>Webhook URL</span><input readOnly value={url}/></label><button className="n8n-btn" onClick={()=>void navigator.clipboard.writeText(url)}>Copy URL</button><p>Send POST with the x-switchboard-secret header.</p>{trigger&&<button className="n8n-btn" onClick={()=>void rotate()}>Rotate secret</button>}{secret&&<><p>Copy this secret now. It is only shown once.</p><button className="n8n-btn" onClick={()=>void navigator.clipboard.writeText(secret)}>Copy secret</button></>}</>}<p role="status">{message}</p></section>
}
