'use client';
import {useEffect,useRef,useState} from 'react';
import {getSession,sb} from '../lib/switchboard';
export function WorkflowDetails({workflow,onClose,onSaved}:{workflow:any;onClose:()=>void;onSaved:(saved:any)=>void}){
 const dialog=useRef<HTMLDialogElement>(null);const[name,setName]=useState(workflow.name),[description,setDescription]=useState(workflow.description||''),[permitted,setPermitted]=useState<string[]>(workflow.permittedUserIds||[]),[users,setUsers]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const admin=getSession()?.user?.role==='ADMIN';
 useEffect(()=>{dialog.current?.showModal();if(admin)void sb<any[]>('/users?limit=200').then(setUsers).catch(e=>setError(e.message))},[admin]);
 return <dialog ref={dialog} onCancel={onClose} className="workflow-dialog" aria-labelledby="workflow-details-title"><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{const saved=await sb(`/workflows/${workflow.id}`,{method:'PUT',body:JSON.stringify({name,description,...(admin?{permittedUserIds:permitted}:{})})});onSaved(saved);onClose()}catch(e){setError(e instanceof Error?e.message:'Could not save details')}finally{setBusy(false)}}}><h2 id="workflow-details-title">Workflow details</h2><label>Name<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)}/></label>{admin&&<fieldset><legend>Permitted users</legend><p>Operators may execute. Viewers may read. Editing stays with the owner and administrators.</p>{users.map(user=><label key={user.id}><input type="checkbox" checked={permitted.includes(user.id)} onChange={e=>setPermitted(ids=>e.target.checked?[...ids,user.id]:ids.filter(id=>id!==user.id))}/>{user.name} · {user.role}</label>)}</fieldset>}{error&&<p role="alert">{error}</p>}<footer><button type="button" onClick={onClose}>Cancel</button><button disabled={busy}>{busy?'Saving…':'Save details'}</button></footer></form></dialog>
}
