"use client";
import {useCallback,useEffect,useMemo,useState} from 'react';
import {ReactFlow,Background,Controls,MiniMap,addEdge,useNodesState,useEdgesState,Handle,Position,MarkerType,NodeProps} from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import {Play,Square,Plus,Search,Workflow,Activity,CheckCircle2,Clock3,Users,Database,Globe2,Terminal,Mail,GitBranch,Webhook,ShieldCheck,ChevronDown,Sparkles,Settings2,PanelLeftClose,Zap,X} from 'lucide-react';
import {sb} from '../lib/switchboard';

type Status='idle'|'running'|'done'|'failed';
type Data={label:string,kind:string,subtitle?:string,status?:Status,config?:Record<string,unknown>,retry?:number,continueOnFailure?:boolean};
const palette=[
 ['trigger','New Employee','Trigger',Users],['createUser','Create User','Directory',Plus],['condition','Condition','Logic',GitBranch],['addGroup','Add Group','Access',ShieldCheck],['assignLicense','Assign License','SaaS',Sparkles],['email','Send Email','Email',Mail],['http','HTTP Request','Integration',Globe2],['postgres','PostgreSQL','Database',Database],['webhook','Webhook','Trigger',Webhook],['ssh','SSH Action','Systems',Terminal],['powershell','PowerShell','Systems',Terminal],['health','Health Check','Monitoring',Activity],['delay','Delay','Control',Clock3],['approval','Approval','Control',Clock3],['disableUser','Disable User','Directory',Users]
] as const;
const iconMap:any={trigger:Users,createUser:Zap,disableUser:Users,addGroup:ShieldCheck,assignLicense:Sparkles,condition:GitBranch,email:Mail,http:Globe2,postgres:Database,webhook:Webhook,ssh:Terminal,powershell:Terminal,health:Activity,delay:Clock3,approval:Clock3};
function FlowNode({data,selected}:NodeProps){const d=data as Data;const Icon=iconMap[d.kind]||Zap;return <div className={`flow-node ${d.kind} ${selected?'selected':''} ${d.status||''}`}><Handle type="target" position={Position.Top}/><div className="node-head"><span className="node-icon"><Icon size={15}/></span><span className="node-type">{d.kind}</span>{d.status==='done'&&<CheckCircle2 size={15} className="ok"/>}{d.status==='running'&&<span className="pulse"/>}{d.status==='failed'&&<X size={15}/>}</div><strong>{d.label}</strong><small>{d.subtitle||'Ready to configure'}</small><Handle type="source" position={Position.Bottom}/></div>}
const initialNodes:any[]=[
 {id:'1',type:'custom',position:{x:410,y:40},data:{label:'New Employee',kind:'trigger',subtitle:'Manual / webhook trigger',status:'idle'}},
 {id:'2',type:'custom',position:{x:410,y:190},data:{label:'Create User',kind:'createUser',subtitle:'Internal directory',status:'idle',config:{email:'{{trigger.email}}',fullName:'{{trigger.fullName}}',department:'{{trigger.department}}',title:'{{trigger.title}}'}}},
 {id:'3',type:'custom',position:{x:410,y:340},data:{label:'Is IT?',kind:'condition',subtitle:'Route by department',status:'idle',config:{field:'trigger.department',operator:'equals',value:'IT'}}},
 {id:'4',type:'custom',position:{x:220,y:500},data:{label:'IT Group',kind:'addGroup',subtitle:'Add to IT-Engineering',status:'idle',config:{email:'{{trigger.email}}',group:'IT-Engineering'}}},
 {id:'5',type:'custom',position:{x:600,y:500},data:{label:'Finance Group',kind:'addGroup',subtitle:'Add to Finance-Core',status:'idle',config:{email:'{{trigger.email}}',group:'Finance-Core'}}},
 {id:'6',type:'custom',position:{x:220,y:650},data:{label:'Assign GitHub',kind:'assignLicense',subtitle:'GitHub Enterprise',status:'idle',config:{email:'{{trigger.email}}',license:'GitHub-Enterprise'}}},
 {id:'7',type:'custom',position:{x:600,y:650},data:{label:'Assign Excel',kind:'assignLicense',subtitle:'Microsoft 365',status:'idle',config:{email:'{{trigger.email}}',license:'Microsoft-365'}}},
];
const initialEdges:any[]=[
 {id:'e1',source:'1',target:'2',animated:true},{id:'e2',source:'2',target:'3',animated:true},
 {id:'e3',source:'3',target:'4',animated:true,data:{when:'true'},label:'TRUE'},
 {id:'e4',source:'3',target:'5',animated:true,data:{when:'false'},label:'FALSE'},
 {id:'e5',source:'4',target:'6',animated:true},{id:'e6',source:'5',target:'7',animated:true}
].map(e=>({...e,markerEnd:{type:MarkerType.ArrowClosed},style:{strokeWidth:2}}));

export default function Page(){
 const [nodes,setNodes,onNodesChange]=useNodesState(initialNodes);const [edges,setEdges,onEdgesChange]=useEdgesState(initialEdges);const [logs,setLogs]=useState<string[]>(['Connecting to engine…']);const [running,setRunning]=useState(false);const [selected,setSelected]=useState<any>(null);const [query,setQuery]=useState('');const [workflowId,setWorkflowId]=useState<string|null>(null);const [online,setOnline]=useState(false);const [showTrigger,setShowTrigger]=useState(false);const [employee,setEmployee]=useState({fullName:'Ghala AlHashmi',email:'ghala@switchboard.dev',department:'IT',title:'Software Engineer'});
 const nodeTypes=useMemo(()=>({custom:FlowNode}),[]);const onConnect=useCallback((p:any)=>setEdges(es=>addEdge({...p,animated:true,markerEnd:{type:MarkerType.ArrowClosed}},es)),[setEdges]);
 useEffect(()=>{(async()=>{try{const ws=await sb<any[]>('/workflows');let w=ws.find(x=>x.slug==='employee-onboarding');if(!w)w=await sb('/workflows',{method:'POST',body:JSON.stringify({name:'Employee Onboarding',slug:'employee-onboarding',status:'ACTIVE',definition:{nodes,edges}})});setWorkflowId(w.id);setOnline(true);setLogs(['Engine online. Workflow loaded.'])}catch(e:any){setOnline(false);setLogs([`Engine offline: ${e.message}`])}})()},[]);
 function addNode(kind:string,label:string){const id=crypto.randomUUID();setNodes(ns=>[...ns,{id,type:'custom',position:{x:330+Math.random()*260,y:160+Math.random()*450},data:{label,kind,subtitle:'Click to configure',status:'idle',config:{}}}])}
 async function saveGraph(){if(!workflowId)throw new Error('Workflow not loaded');return sb(`/workflows/${workflowId}`,{method:'PUT',body:JSON.stringify({definition:{nodes:nodes.map(n=>({...n,data:{...n.data,status:'idle'}})),edges}})})}
 async function run(){if(running||!workflowId)return;setShowTrigger(false);setRunning(true);setNodes(ns=>ns.map(n=>({...n,data:{...n.data,status:'idle'}})));try{await saveGraph();const started=await sb<any>(`/workflows/${workflowId}/run`,{method:'POST',body:JSON.stringify({triggerType:'manual',payload:employee})});setLogs([`Run ${started.id} queued…`]);let done=false;while(!done){await new Promise(r=>setTimeout(r,650));const r=await sb<any>(`/runs/${started.id}`);setLogs(r.logs.map((x:any)=>x.message));const states=new Map(r.steps.map((s:any)=>[s.nodeId,s.status]));setNodes(ns=>ns.map(n=>{const s=states.get(n.id);return {...n,data:{...n.data,status:s==='RUNNING'?'running':s==='SUCCEEDED'?'done':s==='FAILED'?'failed':n.data.status}}}));done=['SUCCEEDED','FAILED','WAITING','CANCELLED'].includes(r.status);if(done&&r.status==='FAILED')throw new Error(r.error||'Workflow failed')} }catch(e:any){setLogs(l=>[...l,`ERROR: ${e.message}`])}finally{setRunning(false)}}
 const filtered=palette.filter(x=>x[1].toLowerCase().includes(query.toLowerCase())||x[2].toLowerCase().includes(query.toLowerCase()));
 return <main className="app">
  <header><div className="brand"><div className="logo"><Workflow size={21}/></div><div><b>SWITCHBOARD</b><span>IT AUTOMATION OS</span></div></div><div className="workflow-title"><span className={online?'live-dot':'offline-dot'}/>Employee Onboarding <ChevronDown size={14}/><em>{online?'Engine connected':'Engine offline'}</em></div><div className="top-actions"><button className="ghost" onClick={()=>saveGraph().then(()=>setLogs(l=>[...l,'Workflow saved']))}><Settings2 size={16}/> Save</button><button className="run" disabled={!online||running} onClick={()=>setShowTrigger(true)}>{running?<><Square size={15}/> Running…</>:<><Play size={15}/> Run workflow</>}</button></div></header>
  <section className="body"><aside className="library"><div className="aside-title"><span>NODE LIBRARY</span><PanelLeftClose size={16}/></div><div className="search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search nodes…"/></div><div className="node-list">{filtered.map(([kind,label,cat,Icon])=><button key={label} className="palette-node" onClick={()=>addNode(kind,label)}><span><Icon size={17}/></span><div><b>{label}</b><small>{cat}</small></div><Plus size={14} className="add"/></button>)}</div><div className="tip"><Sparkles size={16}/><div><b>Real engine connected.</b><p>Graph execution, retries, branching and run logs are persisted.</p></div></div></aside>
   <div className="canvas"><div className="canvas-toolbar"><span><Workflow size={15}/> Workflow canvas</span><span className="env">● DEVELOPMENT</span></div><ReactFlow nodes={nodes} edges={edges} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} onConnect={onConnect} onNodeClick={(_,n)=>setSelected(n)} nodeTypes={nodeTypes} fitView><Background gap={22} size={1}/><Controls/><MiniMap zoomable pannable/></ReactFlow></div>
   <aside className="inspector"><div className="panel-tabs"><button className="active">Inspector</button><button>Runs</button></div>{selected?<div className="config"><div className="config-icon"><Zap size={20}/></div><h3>{selected.data.label}</h3><p>{String(selected.data.kind).toUpperCase()} NODE</p><label>Display name<input value={selected.data.label} onChange={e=>{const v=e.target.value;setNodes(ns=>ns.map(n=>n.id===selected.id?{...n,data:{...n.data,label:v}}:n));setSelected({...selected,data:{...selected.data,label:v}})}}/></label><label>Retries<select value={selected.data.retry||0} onChange={e=>{const retry=Number(e.target.value);setNodes(ns=>ns.map(n=>n.id===selected.id?{...n,data:{...n.data,retry}}:n));setSelected({...selected,data:{...selected.data,retry}})}}><option value="0">No retry</option><option value="1">Retry once</option><option value="3">Retry 3 times</option></select></label><label>Config (JSON)<textarea value={JSON.stringify(selected.data.config||{},null,2)} onChange={e=>{try{const config=JSON.parse(e.target.value);setNodes(ns=>ns.map(n=>n.id===selected.id?{...n,data:{...n.data,config}}:n));setSelected({...selected,data:{...selected.data,config}})}catch{}}}/></label></div>:<div className="empty"><Settings2/><h3>Select a node</h3><p>Configure inputs, retries and connector settings.</p></div>}<div className="execution"><div className="exec-head"><b>LIVE EXECUTION</b><span>{running?'RUNNING':online?'READY':'OFFLINE'}</span></div><div className="logs">{logs.slice(-12).map((l,i)=><div key={i} className={l.startsWith('✓')||l.includes('success')?'success':''}>{l}</div>)}</div></div></aside>
  </section><footer><span><span className={online?'live-dot':'offline-dot'}/> {online?'Engine online':'Engine offline'}</span><span>{palette.length} node types</span><span>Persistent run history</span><span className="right">v1.0.0 · PostgreSQL engine</span></footer>
  {showTrigger&&<div className="modal-backdrop"><div className="trigger-modal"><button className="modal-x" onClick={()=>setShowTrigger(false)}><X/></button><span className="eyebrow">NEW EMPLOYEE TRIGGER</span><h2>Start onboarding</h2><p>This payload becomes <code>trigger.*</code> inside every node.</p><label>Full name<input value={employee.fullName} onChange={e=>setEmployee({...employee,fullName:e.target.value})}/></label><label>Email<input value={employee.email} onChange={e=>setEmployee({...employee,email:e.target.value})}/></label><label>Department<select value={employee.department} onChange={e=>setEmployee({...employee,department:e.target.value})}><option>IT</option><option>Finance</option><option>HR</option><option>Operations</option></select></label><label>Job title<input value={employee.title} onChange={e=>setEmployee({...employee,title:e.target.value})}/></label><button className="start-run" onClick={run}><Play size={16}/> Start onboarding</button></div></div>}
 </main>
}
