import Link from 'next/link';
import {Activity,ArrowRight,ArrowUpRight,CheckCircle2,Clock3,GitBranch,Globe2,LockKeyhole,Network,Play,ShieldCheck,Workflow,Zap} from 'lucide-react';
import './landing-premium.css';
export default function Landing(){
 return <main className="lp-site">
  <header className="lp-nav"><Link href="/" className="lp-brand"><span><Network size={23}/></span><b>SWITCHBOARD</b></Link><nav aria-label="Site navigation"><a href="#product">Product</a><a href="#capabilities">Capabilities</a></nav><div className="lp-nav-actions"><Link href="/login" className="lp-signin">Sign in</Link><Link href="/signup" className="lp-btn lp-btn-primary">Get started <ArrowUpRight size={15}/></Link></div></header>
  <section className="lp-hero" id="product"><div className="lp-hero-copy"><div className="lp-eyebrow"><span/> THE VISUAL IT AUTOMATION PLATFORM</div><h1>Complex workflows.<br/><em>Beautifully simple.</em></h1><p>Design automations, connect the tools your team relies on, and see exactly what happens at every step. One visual workspace, from trigger to outcome.</p><div className="lp-hero-buttons"><Link href="/signup" className="lp-btn lp-btn-primary">Start building <ArrowRight size={17}/></Link><Link href="/login" className="lp-btn lp-btn-secondary"><Play size={16}/> Open workspace</Link></div><div className="lp-highlights"><span><CheckCircle2 size={15}/> Visual workflow builder</span><span><CheckCircle2 size={15}/> Run-level observability</span><span><CheckCircle2 size={15}/> Secure access controls</span></div></div>
   <div className="lp-preview" aria-label="Example employee onboarding workflow"><div className="lp-preview-head"><div><span className="lp-preview-icon"><Workflow size={18}/></span><div><b>Employee onboarding</b><small>WORKFLOW PREVIEW</small></div></div><span className="lp-preview-pill">EXAMPLE</span></div><div className="lp-preview-canvas"><div className="lp-flow-item"><span className="lp-flow-symbol start"><Zap size={18}/></span><div><small>TRIGGER</small><b>New employee</b><p>Start with an event</p></div><span className="lp-flow-status"><CheckCircle2 size={16}/></span></div><div className="lp-flow-connector"/><div className="lp-flow-item"><span className="lp-flow-symbol action"><Globe2 size={18}/></span><div><small>ACTION</small><b>Create directory user</b><p>Configure and run a node</p></div><span className="lp-flow-status"><CheckCircle2 size={16}/></span></div><div className="lp-flow-connector"/><div className="lp-flow-item"><span className="lp-flow-symbol logic"><GitBranch size={18}/></span><div><small>CONDITION</small><b>Route by department</b><p>Branch based on your data</p></div><span className="lp-flow-status logic"><GitBranch size={16}/></span></div><div className="lp-flow-forks"><div><span/>IT team<ArrowRight size={13}/></div><div><span/>Other team<ArrowRight size={13}/></div></div></div><div className="lp-preview-foot"><span><Activity size={16}/> Step-by-step visibility</span><span>DESIGN → EXECUTE → OBSERVE</span></div></div>
  </section>
  <section className="lp-features" id="capabilities"><div className="lp-section-title"><span>BUILT FOR THE WAY IT WORKS</span><h2>One platform. The whole workflow.</h2><p>From a simple API call to multi-step operational processes.</p></div><div className="lp-feature-grid"><article><div className="lp-feature-icon"><Workflow size={21}/></div><h3>Build visually</h3><p>Drag, connect, configure, and save workflows on an interactive canvas — with branching conditions and reusable actions.</p></article><article><div className="lp-feature-icon"><Activity size={21}/></div><h3>Understand every run</h3><p>See step statuses, logs, outputs, and failures without guessing what happened behind the scenes.</p></article><article><div className="lp-feature-icon"><LockKeyhole size={21}/></div><h3>Operate with control</h3><p>Manage credentials, user roles, triggers, and audit activity from one workspace.</p></article></div></section>
  <section className="lp-cta"><div><span>READY TO AUTOMATE?</span><h2>Turn repetitive work into reliable workflows.</h2><p>Create a workspace and start connecting your process.</p></div><Link href="/signup" className="lp-btn lp-btn-primary">Create your account <ArrowRight size={18}/></Link></section>
  <footer className="lp-footer"><span><Network size={17}/> SWITCHBOARD</span><span>Visual IT Automation · Built for operators and engineers</span><Link href="/login">Sign in <ArrowUpRight size={13}/></Link></footer>
 </main>;
}
