import {validateCredentials} from '../services/workflow-credentials.service.js';
import type{Request,Response}from'express';import*as service from'../services/workflow.service.js';import{workflowSchema}from'../validators/workflow.validator.js';import{audit}from'../services/audit.service.js';const param=(v:string|string[])=>Array.isArray(v)?v[0]:v;
export async function list(req:Request,res:Response){return res.json(await service.list(req.user!))}
export async function create(req:Request,res:Response){const input=workflowSchema.parse(req.body);if(input.permittedUserIds&&req.user!.role!=='ADMIN')return res.status(403).json({error:'Only administrators can grant workflow access'});await validateCredentials(input.definition,undefined,req.user!);const w=await service.create(input,req.user!.id);await audit(req,'workflow.created','Workflow',w.id);return res.status(201).json(w)}
export async function get(req:Request,res:Response){const w=await service.find(param(req.params.id));if(!service.canAccess(w,req.user!))return res.status(403).json({error:'Forbidden'});return res.json(w)}
export async function update(req:Request,res:Response){const id=param(req.params.id);const current=await service.find(id);if(!service.canEdit(current,req.user!))return res.status(403).json({error:'Forbidden'});const input=workflowSchema.partial().parse(req.body);if(input.permittedUserIds&&req.user!.role!=='ADMIN')return res.status(403).json({error:'Only administrators can grant workflow access'});if(input.definition)await validateCredentials(input.definition,id,req.user!);const w=await service.update(id,input);await audit(req,'workflow.updated','Workflow',w.id,{version:w.version});return res.json(w)}
export async function remove(req:Request,res:Response){const id=param(req.params.id);const w=await service.find(id);if(!service.canEdit(w,req.user!))return res.status(403).json({error:'Forbidden'});await service.remove(id);await audit(req,'workflow.deleted','Workflow',id);return res.status(204).end()}
export async function run(req:Request,res:Response){const id=param(req.params.id);const w=await service.find(id);if(!service.canAccess(w,req.user!))return res.status(403).json({error:'Forbidden'});if(w.status==='ARCHIVED')return res.status(409).json({error:'Archived workflows cannot run'});const r=await service.run(id,req.body?.triggerType||'manual',req.body?.payload||{});await audit(req,'workflow.run.started','Workflow',id,{runId:r.id});return res.status(202).json(r)}
export async function runs(req:Request,res:Response){const id=param(req.params.id);const w=await service.find(id);if(!service.canAccess(w,req.user!))return res.status(403).json({error:'Forbidden'});return res.json(await service.runs(id))}
