'use client';
import {FormEvent,useEffect,useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';
import {Activity,ArrowRight,Clock3,Filter,Network,Play,Plus,RefreshCw,Search,Workflow} from 'lucide-react';
import {Shell} from '../../components/Shell';
import {sb} from '../../lib/switchboard';

const runFilters=['ALL','RUNNING','SUCCEEDED','FAILED','WAITING'];
export default function WorkflowsPage(){
 const router=useRouter();
 const[workflows,setWorkflows]=useState<any[]>([]),[runs,setRuns]=useState<any[]>([]),[name,setName]=useState(''),[slug,setSlug]=useState(''),[query,setQuery]=useState(''),[runFilter,setRunFilter]=useState('ALL'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[refreshing,setRefreshing]=useState(false),[runningId,setRunningId]=useState('');
 const load=async(silent=false)=>{if(!silent)setRefreshing(true);try{const[w,r]=await Promise.all([sb<any[]>('/workflows'),sb<any[]>('/runs')]);setWorkflows(w);setRuns(r);setError('')}catch(e:any){setError(e.message)}finally{setRefreshing(false)}};
 useEffect(()=>{void load();const id=setInterval(()=>void load(true),4000);return()=>clearInterval(id)},[]);
 async function create(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const created=await sb<any>('/workflows',{method:'POST',body:JSON.stringify({name,slug:slug||name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),status:'DRAFT',definition:{nodes:[{id:'start',type:'custom',position:{x:180,y:260},data:{label:'Manual Trigger',kind:'trigger',config:{}}}],edges:[]}})});router.push(`/workflows/${created.id}`)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function runNow(id:string){setRunningId(id);setError('');try{const r=await sb<any>(`/workflows/${id}/run`,{method:'POST',body:JSON.stringify({triggerType:'manual',payload:{source:'workspace',initiatedAt:new Date().toISOString()}})});router.push(`/runs/${r.id}`)}catch(e:any){setError(e.message)}finally{setRunningId('')}}
 const filteredWorkflows=useMemo(()=>workflows.filter(w=>`${w.name} ${w.slug} ${w.status}`.toLowerCase().includes(query.toLowerCase())),[workflows,query]);
 const visibleRuns=useMemo(()=>runs.filter(r=>runFilter==='ALL'||r.status===runFilter).slice(0,12),[runs,runFilter]);
 const counts=useMemo(()=>({active:workflows.filter(w=>w.status==='ACTIVE').length,running:runs.filter(r=>['RUNNING','QUEUED','WAITING'].includes(r.status)).length,success:runs.filter(r=>r.status==='SUCCEEDED').length,failed:runs.filter(r=>r.status==='FAILED').length}),[workflows,runs]);
 return <Shell title="Automation workspace" eyebrow="WORKFLOWS FIRST"><div className="automation-home">
   {error&&<div className="error-panel">{error}</div>}
   <section className="automation-hero"><div><span className="automation-kicker">BUILD · CONNECT · EXECUTE</span><h2>Your automation control surface.</h2><p>Create workflows, wire nodes, run them and inspect every execution from one place.</p></div><form className="automation-create" onSubmit={create}><input value={name} onChange={e=>setName(e.target.value)} placeholder="Workflow name" required/><input value={slug} onChange={e=>setSlug(e.target.value)} placeholder="slug optional"/><button disabled={busy}><Plus size={15}/>{busy?'Creating…':'New workflow'}</button></form></section>
   <section className="automation-metrics"><div><span>Workflows</span><b>{workflows.length}</b><small>{counts.active} active</small></div><div><span>Running now</span><b>{counts.running}</b><small>live executions</small></div><div><span>Succeeded</span><b>{counts.success}</b><small>all recorded runs</small></div><div><span>Failed</span><b>{counts.failed}</b><small>needs attention</small></div></section>
   <div className="automation-grid">
    <section className="automation-panel workflow-panel"><div className="automation-panel-head"><div><small>PRIMARY WORKSPACE</small><h3>Workflows</h3></div><div className="automation-tools"><div className="automation-search"><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search workflows"/></div><button className="icon-action" onClick={()=>void load()} title="Refresh"><RefreshCw size={14} className={refreshing?'spin':''}/></button></div></div>
     <div className="workflow-table-head"><span>Workflow</span><span>Status</span><span>Updated</span><span>Actions</span></div>
     <div className="workflow-table">{filteredWorkflows.map(w=><div className="workflow-row" key={w.id}><button className="workflow-main" onClick={()=>router.push(`/workflows/${w.id}`)}><span className="workflow-icon"><Workflow size={16}/></span><span><b>{w.name}</b><small>{w.slug} · v{w.version}</small></span></button><span className={`status-chip ${String(w.status).toLowerCase()}`}>{w.status}</span><span className="workflow-date">{new Date(w.updatedAt).toLocaleString()}</span><div className="workflow-actions"><button onClick={()=>runNow(w.id)} disabled={runningId===w.id}><Play size={13}/>{runningId===w.id?'Running':'Run'}</button><button onClick={()=>router.push(`/workflows/${w.id}`)}>Open <ArrowRight size={13}/></button></div></div>)}{!filteredWorkflows.length&&<div className="automation-empty"><Network size={22}/><b>No workflows found</b><small>Create one above or change your search.</small></div>}</div>
    </section>
    <section className="automation-panel runs-panel"><div className="automation-panel-head"><div><small>EXECUTION HISTORY</small><h3>Runs</h3></div><Activity size={17}/></div><div className="run-filterbar"><Filter size={12}/>{runFilters.map(f=><button key={f} className={runFilter===f?'active':''} onClick={()=>setRunFilter(f)}>{f}</button>)}</div><div className="run-stream">{visibleRuns.map(r=><button key={r.id} className="run-stream-row" onClick={()=>router.push(`/runs/${r.id}`)}><span className={`run-dot ${String(r.status).toLowerCase()}`}/><span className="run-stream-main"><b>{r.workflow?.name||r.workflowId}</b><small>{r.triggerType} · {new Date(r.createdAt).toLocaleString()}</small></span><span className="run-stream-status">{r.status}</span><ArrowRight size={13}/></button>)}{!visibleRuns.length&&<div className="automation-empty compact"><Clock3 size={20}/><b>No runs yet</b><small>Run a workflow and it will appear here instantly.</small></div>}</div></section>
   </div>
 </div></Shell>
}
