function node(id:string,kind:string,label:string,config:Record<string,unknown>={},x=0,y=0){return{id,type:'custom',position:{x:100+x*300,y:150+y*180},data:{kind,label,config}}}
function edge(source:string,target:string,when?:string){return{id:`${source}-${target}`,source,target,...(when?{sourceHandle:when,data:{when}}:{})}}
const email='{{trigger.email}}';
export const workflowTemplates=[
 {name:'Employee onboarding',definition:{nodes:[node('start','trigger','New employee'),node('create','createUser','Create user',{email,fullName:'{{trigger.fullName}}',department:'{{trigger.department}}'},1),node('department','condition','IT department?',{field:'trigger.department',operator:'equals',value:'IT'},2),node('group','addGroup','Add IT group',{email,group:'IT'},3),node('license','assignLicense','Assign license',{email,license:'Standard'},4),node('welcome','email','Send welcome',{to:email,subject:'Welcome',text:'Your account is ready.'},5)],edges:[edge('start','create'),edge('create','department'),edge('department','group','true'),edge('department','welcome','false'),edge('group','license'),edge('license','welcome')]}},
 {name:'Employee offboarding',definition:{nodes:[node('start','trigger','Employee departure'),node('disable','disableUser','Disable user',{email},1),node('group','removeGroup','Remove group',{email,group:'IT'},2),node('license','revokeLicense','Revoke license',{email,license:'Standard'},3),node('notify','email','Notify administrator',{to:'{{trigger.adminEmail}}',subject:'Offboarding complete',text:'Access has been removed.'},4)],edges:[edge('start','disable'),edge('disable','group'),edge('group','license'),edge('license','notify')]}},
 {name:'Server health monitoring',definition:{nodes:[node('start','schedule','Every five minutes',{every:5,unit:'minutes'}),node('health','health','Check server',{url:'https://switchboard-api-tqc3.onrender.com/health',expectedStatus:200},1),node('condition','condition','Healthy?',{field:'outputs.health.ok',operator:'equals',value:'true'},2),node('ok','noop','Healthy',{},3),node('alert','email','Send alert',{to:'{{trigger.adminEmail}}',subject:'Health check failed',text:'The monitored service needs attention.'},3,1)],edges:[edge('start','health'),edge('health','condition'),edge('condition','ok','true'),edge('condition','alert','false')]}},
 {name:'API health workflow',definition:{nodes:[node('start','trigger','Test API'),node('http','http','API request',{method:'GET',url:'https://switchboard-api-tqc3.onrender.com/health',allowNon2xx:true},1),node('condition','condition','Status 200?',{field:'outputs.http.status',operator:'equals',value:'200'},2),node('ok','noop','API healthy',{},3),node('alert','email','Email alert',{to:'{{trigger.adminEmail}}',subject:'API check failed',text:'An unexpected response was received.'},3,1)],edges:[edge('start','http'),edge('http','condition'),edge('condition','ok','true'),edge('condition','alert','false')]}}
];
