'use client';
import {FormEvent,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {ArrowLeft,ArrowRight,CheckCircle2,Eye,EyeOff,LockKeyhole,Network} from 'lucide-react';
import {sb,setSession} from '../../lib/switchboard';
export default function Login(){
 const router=useRouter();
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[showPassword,setShowPassword]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const r=await sb<any>('/auth/login',{method:'POST',body:JSON.stringify({email:email.trim(),password}),auth:false});setSession(r.token,r.user);router.replace('/workflows')}catch(e:any){setError(e?.message||'Unable to sign in. Please retry.')}finally{setBusy(false)}}
 return <main className="terminal-auth sb-auth"><Link href="/" className="terminal-back"><ArrowLeft size={16}/> Back to home</Link><div className="terminal-auth-wrap"><section className="terminal-auth-copy"><Link href="/" className="terminal-mark"><span className="sb-auth-logo"><Network size={20}/></span><span>SWITCHBOARD</span></Link><small>YOUR AUTOMATION WORKSPACE</small><h1>Everything in<br/>sync. <em>In one place.</em></h1><p>Design workflows, connect services, and follow every execution with a clear view of your IT operations.</p><div className="terminal-lines"><span><CheckCircle2 size={16}/>Visual workflow builder</span><span><CheckCircle2 size={16}/>Detailed execution history</span><span><CheckCircle2 size={16}/>Secure credential management</span></div></section><form className="terminal-form" onSubmit={submit}><header><span>WELCOME BACK</span><LockKeyhole size={17}/></header><h2>Sign in to Switchboard</h2><p className="sb-form-subtitle">Enter your account details to access your workspace.</p><label htmlFor="login-email">Email address</label><input id="login-email" type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="username" required placeholder="you@company.com"/><label htmlFor="login-password">Password</label><div className="sb-password-field"><input id="login-password" type={showPassword?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required placeholder="Enter your password"/><button type="button" onClick={()=>setShowPassword(x=>!x)} aria-label={showPassword?'Hide password':'Show password'}>{showPassword?<EyeOff size={18}/>:<Eye size={18}/>}</button></div>{error&&<div className="terminal-error" role="alert">{error}</div>}<button className="terminal-submit" disabled={busy}>{busy?'Signing in…':'Sign in'} <ArrowRight size={17}/></button><small>New to Switchboard? <Link href="/signup">Create an account</Link></small></form></div></main>;
}