'use client';
import {FormEvent,useEffect,useMemo,useState} from 'react';
import {Check,Copy,KeyRound,Play,Plus,RefreshCw,Trash2,Webhook,Zap} from 'lucide-react';
import {Shell} from '../../components/Shell';
import {sb} from '../../lib/switchboard';
const API='https://switchboard-api-tqc3.onrender.com';
export default function TriggersPage(){
 const[workflows,setWorkflows]=useState<any[]>([]),[workflowId,setWorkflowId]=useState(''),[rows,setRows]=useState<any[]>([]),[runs,setRuns]=useState<any[]>([]),[type,setType]=useState('WEBHOOK'),[every,setEvery]=useState(15),[unit,setUnit]=useState('minutes'),[secret,setSecret]=useState(''),[testSecret,setTestSecret]=useState(''),[testPayload,setTestPayload]=useState('{"event":"test","source":"switchboard"}'),[testResult,setTestResult]=useState(''),[error,setError]=useState(''),[copied,setCopied]=useState('');
 useEffect(()=>{sb<any[]>('/workflows').then(ws=>{setWorkflows(ws);if(ws[0])setWorkflowId(ws[0].id)}).catch(e=>setError(e.message))},[]);
 useEffect(()=>{if(workflowId)void load()},[workflowId]);
 const workflow=workflows.find(w=>w.id===workflowId);const webhookUrl=workflow?`${API}/api/webhooks/${workflow.slug}`:'';
 async function load(){try{const[t,r]=await Promise.all([sb<any[]>(`/triggers/workflow/${workflowId}`),sb<any[]>(`/runs?workflowId=${workflowId}`)]);setRows(t);setRuns(r);setError('')}catch(e:any){setError(e.message)}}
 async function create(e:FormEvent){e.preventDefault();try{const config=type==='SCHEDULE'?{every,unit}:{};const t=await sb<any>(`/triggers/workflow/${workflowId}`,{method:'POST',body:JSON.stringify({type,enabled:true,config})});if(t.secret){setSecret(t.secret);setTestSecret(t.secret)}await load()}catch(e:any){setError(e.message)}}
 async function rotate(id:string){try{const r=await sb<any>(`/triggers/${id}/rotate-secret`,{method:'POST',body:'{}'});setSecret(r.secret);setTestSecret(r.secret);await load()}catch(e:any){setError(e.message)}}
 async function toggle(r:any){try{await sb(`/triggers/${r.id}`,{method:'PATCH',body:JSON.stringify({enabled:!r.enabled})});await load()}catch(e:any){setError(e.message)}}
 async function remove(id:string){if(!confirm('Delete this trigger?'))return;try{await sb(`/triggers/${id}`,{method:'DELETE'});await load()}catch(e:any){setError(e.message)}}
 async function copy(value:string,key:string){await navigator.clipboard.writeText(value);setCopied(key);setTimeout(()=>setCopied(''),1200)}
 async function testWebhook(){setTestResult('Sending…');try{const payload=JSON.parse(testPayload||'{}');const r=await fetch(webhookUrl,{method:'POST',headers:{'content-type':'application/json','x-switchboard-secret':testSecret},body:JSON.stringify(payload)});const data=await r.json().catch(()=>({}));setTestResult(r.ok?`Accepted · ${data.runId||'queued'}`:`${r.status} · ${data.error||'Request failed'}`);await load()}catch(e:any){setTestResult(e.message)}}
 const recentWebhook=useMemo(()=>runs.find(r=>String(r.triggerType).startsWith('webhook:')||r.triggerType==='webhook'),[runs]);
 return <Shell title="Triggers" eyebrow="AUTOMATION ENTRY POINTS"><div className="trigger-modern">{error&&<div className="error-panel">{error}</div>}
  <section className="trigger-toolbar"><label>Workflow<select value={workflowId} onChange={e=>setWorkflowId(e.target.value)}>{workflows.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><form onSubmit={create}><select value={type} onChange={e=>setType(e.target.value)}><option>WEBHOOK</option><option>SCHEDULE</option><option>MANUAL</option></select>{type==='SCHEDULE'&&<><input type="number" min="1" value={every} onChange={e=>setEvery(Number(e.target.value))}/><select value={unit} onChange={e=>setUnit(e.target.value)}><option>minutes</option><option>hours</option><option>days</option></select></>}<button disabled={!workflowId}><Plus size={14}/>Add trigger</button></form><button className="trigger-refresh" onClick={()=>void load()}><RefreshCw size={14}/></button></section>
  <div className="trigger-grid"><section className="trigger-card webhook-console"><header><div><small>WEBHOOK ENDPOINT</small><h2>Receive external events</h2></div><Webhook size={20}/></header><label>Endpoint<div className="copy-field"><code>{webhookUrl||'Select a workflow'}</code><button onClick={()=>webhookUrl&&copy(webhookUrl,'url')}>{copied==='url'?<Check size={14}/>:<Copy size={14}/>}</button></div></label>{secret&&<label>New secret<div className="copy-field secret"><code>{secret}</code><button onClick={()=>copy(secret,'secret')}>{copied==='secret'?<Check size={14}/>:<Copy size={14}/>}</button></div><small>This secret is shown after create/rotate. Store it safely.</small></label>}<div className="webhook-test"><div><label>Secret<input type="password" value={testSecret} onChange={e=>setTestSecret(e.target.value)} placeholder="Paste or rotate a webhook secret"/></label><label>Test payload<textarea value={testPayload} onChange={e=>setTestPayload(e.target.value)}/></label></div><button onClick={testWebhook} disabled={!webhookUrl||!testSecret}><Play size={14}/>Send test webhook</button>{testResult&&<p>{testResult}</p>}</div>{recentWebhook&&<div className="last-webhook"><span className={`run-dot ${String(recentWebhook.status).toLowerCase()}`}/><div><b>Last webhook execution</b><small>{recentWebhook.status} · {new Date(recentWebhook.createdAt).toLocaleString()}</small></div></div>}</section>
   <section className="trigger-card"><header><div><small>CONFIGURED</small><h2>{rows.length} triggers</h2></div><Zap size={20}/></header><div className="trigger-list">{rows.map(r=><div className="trigger-row" key={r.id}><span className="trigger-kind">{r.type==='WEBHOOK'?<Webhook size={15}/>:<Zap size={15}/>}</span><div><b>{r.type}</b><small>{r.type==='SCHEDULE'?`Every ${r.config?.every||'?'} ${r.config?.unit||''}`:'Event entry point'}</small></div><span className={`trigger-state ${r.enabled?'enabled':'disabled'}`}>{r.enabled?'Enabled':'Disabled'}</span><div className="trigger-actions"><button onClick={()=>toggle(r)}>{r.enabled?'Disable':'Enable'}</button>{r.type==='WEBHOOK'&&<button onClick={()=>rotate(r.id)}><KeyRound size={13}/>Rotate</button>}<button className="danger" onClick={()=>remove(r.id)}><Trash2 size={13}/></button></div></div>)}{!rows.length&&<div className="trigger-empty">No triggers configured for this workflow.</div>}</div></section></div>
 </div></Shell>}
