'use client';
import {FormEvent,useEffect,useState} from 'react';
import {Database,KeyRound,LockKeyhole,Plus,Server,ShieldCheck,Trash2} from 'lucide-react';
import {Shell} from '../../components/Shell';
import {sb} from '../../lib/switchboard';
const types=['API_KEY','SSH','POSTGRES','SMTP','BASIC_AUTH'] as const;
export default function CredentialsPage(){
 const[rows,setRows]=useState<any[]>([]),[name,setName]=useState(''),[type,setType]=useState<(typeof types)[number]>('API_KEY'),[data,setData]=useState<Record<string,any>>({secret:''}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=()=>sb<any[]>('/credentials').then(setRows).catch(e=>setError(e.message));useEffect(()=>{void load()},[]);
 const set=(k:string,v:any)=>setData(d=>({...d,[k]:v}));
 const reset=(next=type)=>{setData(next==='API_KEY'?{secret:''}:next==='SSH'?{host:'',port:22,username:'',password:'',privateKey:''}:next==='POSTGRES'?{connectionString:'',ssl:true}:next==='SMTP'?{host:'',port:587,username:'',password:''}:{username:'',password:''})};
 async function create(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await sb('/credentials',{method:'POST',body:JSON.stringify({name,type,data})});setName('');reset(type);await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function remove(id:string){if(!confirm('Delete this credential? Existing workflow nodes using it will fail until another credential is selected.'))return;try{await sb(`/credentials/${id}`,{method:'DELETE'});await load()}catch(e:any){setError(e.message)}}
 const changeType=(next:(typeof types)[number])=>{setType(next);reset(next)};
 return <Shell title="Secrets" eyebrow="ENCRYPTED CREDENTIAL VAULT"><div className="automation-home">{error&&<div className="error-panel">{error}</div>}
  <section className="automation-hero"><div><span className="automation-kicker">SECURE · REUSABLE · ENCRYPTED</span><h2>Credentials your nodes can actually use.</h2><p>Create typed secrets once, then select them directly inside HTTP, SSH, PostgreSQL and email nodes.</p></div><div className="secret-badge"><ShieldCheck size={18}/><span><b>Encrypted at rest</b><small>Secret values are never returned by list APIs.</small></span></div></section>
  <div className="credentials-layout"><section className="automation-panel"><div className="automation-panel-head"><div><small>NEW SECRET</small><h3>Create credential</h3></div><KeyRound size={17}/></div><form className="credential-form" onSubmit={create}><label>Name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Production API" required/></label><label>Type<select value={type} onChange={e=>changeType(e.target.value as any)}>{types.map(t=><option key={t}>{t}</option>)}</select></label>
  {type==='API_KEY'&&<label>API key<input type="password" value={data.secret||''} onChange={e=>set('secret',e.target.value)} placeholder="••••••••" required/></label>}
  {type==='SSH'&&<><div className="credential-two"><label>Host<input value={data.host||''} onChange={e=>set('host',e.target.value)} placeholder="10.0.0.10" required/></label><label>Port<input type="number" value={data.port||22} onChange={e=>set('port',Number(e.target.value))}/></label></div><label>Username<input value={data.username||''} onChange={e=>set('username',e.target.value)} required/></label><label>Password<input type="password" value={data.password||''} onChange={e=>set('password',e.target.value)}/></label><label>Private key<textarea value={data.privateKey||''} onChange={e=>set('privateKey',e.target.value)} placeholder="Optional if password is used"/></label></>}
  {type==='POSTGRES'&&<><label>Connection string<input type="password" value={data.connectionString||''} onChange={e=>set('connectionString',e.target.value)} placeholder="postgresql://…" required/></label><label className="checkbox-row"><input type="checkbox" checked={data.ssl!==false} onChange={e=>set('ssl',e.target.checked)}/> Use SSL</label></>}
  {type==='SMTP'&&<><div className="credential-two"><label>SMTP host<input value={data.host||''} onChange={e=>set('host',e.target.value)} placeholder="smtp.example.com" required/></label><label>Port<input type="number" value={data.port||587} onChange={e=>set('port',Number(e.target.value))}/></label></div><label>Username<input value={data.username||''} onChange={e=>set('username',e.target.value)} required/></label><label>Password<input type="password" value={data.password||''} onChange={e=>set('password',e.target.value)} required/></label></>}
  {type==='BASIC_AUTH'&&<><label>Username<input value={data.username||''} onChange={e=>set('username',e.target.value)} required/></label><label>Password<input type="password" value={data.password||''} onChange={e=>set('password',e.target.value)} required/></label></>}
  <button className="primary-btn" disabled={busy}><Plus size={15}/>{busy?'Saving…':'Save encrypted credential'}</button></form></section>
  <section className="automation-panel"><div className="automation-panel-head"><div><small>VAULT INVENTORY</small><h3>{rows.length} stored credentials</h3></div><LockKeyhole size={17}/></div><div className="credential-list">{rows.map(r=><div className="credential-row" key={r.id}><span className="credential-icon">{r.type==='POSTGRES'?<Database size={16}/>:r.type==='SSH'?<Server size={16}/>:<KeyRound size={16}/>}</span><span><b>{r.name}</b><small>{r.type} · updated {new Date(r.updatedAt).toLocaleString()}</small></span><button onClick={()=>remove(r.id)} aria-label="Delete credential"><Trash2 size={14}/></button></div>)}{!rows.length&&<div className="automation-empty"><KeyRound size={22}/><b>No credentials yet</b><small>Create one here, then select it from a workflow node.</small></div>}</div></section></div>
 </div></Shell>
}
